// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240311223121_RelationCircle")]
    partial class RelationCircle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -20,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(530),
                            DateOfBirth = new DateTime(2020, 5, 19, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(513),
                            EnclosureId = -4,
                            Name = "animal_20",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(560),
                            DateOfBirth = new DateTime(2020, 10, 11, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(558),
                            EnclosureId = -1,
                            Name = "animal_21",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -22,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(579),
                            DateOfBirth = new DateTime(2018, 5, 18, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(577),
                            EnclosureId = -3,
                            Name = "animal_22",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -23,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(601),
                            DateOfBirth = new DateTime(2016, 2, 13, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(599),
                            EnclosureId = -3,
                            Name = "animal_23",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -24,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(619),
                            DateOfBirth = new DateTime(2017, 3, 1, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(618),
                            EnclosureId = -4,
                            Name = "animal_24",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -25,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(637),
                            DateOfBirth = new DateTime(2020, 4, 21, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(636),
                            EnclosureId = -5,
                            Name = "animal_25",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(656),
                            DateOfBirth = new DateTime(2018, 1, 6, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(655),
                            EnclosureId = -6,
                            Name = "animal_26",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -27,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(676),
                            DateOfBirth = new DateTime(2016, 8, 17, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(675),
                            EnclosureId = -5,
                            Name = "animal_27",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -28,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(696),
                            DateOfBirth = new DateTime(2020, 7, 1, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(694),
                            EnclosureId = -4,
                            Name = "animal_28",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -29,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(713),
                            DateOfBirth = new DateTime(2022, 6, 21, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(712),
                            EnclosureId = -4,
                            Name = "animal_29",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -30,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(748),
                            DateOfBirth = new DateTime(2019, 6, 12, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(746),
                            EnclosureId = -2,
                            Name = "animal_30",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(767),
                            DateOfBirth = new DateTime(2021, 8, 1, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(766),
                            EnclosureId = -5,
                            Name = "animal_31",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(786),
                            DateOfBirth = new DateTime(2016, 11, 26, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(785),
                            EnclosureId = -1,
                            Name = "animal_32",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -33,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(804),
                            DateOfBirth = new DateTime(2018, 1, 17, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(802),
                            EnclosureId = -5,
                            Name = "animal_33",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(822),
                            DateOfBirth = new DateTime(2017, 6, 15, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(821),
                            EnclosureId = -1,
                            Name = "animal_34",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -35,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(841),
                            DateOfBirth = new DateTime(2017, 3, 7, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(840),
                            EnclosureId = -5,
                            Name = "animal_35",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -36,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(860),
                            DateOfBirth = new DateTime(2022, 11, 14, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(858),
                            EnclosureId = -4,
                            Name = "animal_36",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -37,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(877),
                            DateOfBirth = new DateTime(2018, 9, 5, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(876),
                            EnclosureId = -4,
                            Name = "animal_37",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -38,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(895),
                            DateOfBirth = new DateTime(2016, 8, 28, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(894),
                            EnclosureId = -3,
                            Name = "animal_38",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(913),
                            DateOfBirth = new DateTime(2022, 1, 4, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(912),
                            EnclosureId = -2,
                            Name = "animal_39",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(991),
                            DateOfBirth = new DateTime(2019, 9, 25, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(989),
                            EnclosureId = -6,
                            Name = "animal_40",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1011),
                            DateOfBirth = new DateTime(2024, 2, 23, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1009),
                            EnclosureId = -3,
                            Name = "animal_41",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -42,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1029),
                            DateOfBirth = new DateTime(2020, 8, 5, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1028),
                            EnclosureId = -6,
                            Name = "animal_42",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1047),
                            DateOfBirth = new DateTime(2020, 3, 20, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1045),
                            EnclosureId = -1,
                            Name = "animal_43",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -44,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1065),
                            DateOfBirth = new DateTime(2020, 3, 16, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1063),
                            EnclosureId = -2,
                            Name = "animal_44",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -45,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1082),
                            DateOfBirth = new DateTime(2022, 4, 19, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1081),
                            EnclosureId = -4,
                            Name = "animal_45",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -46,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1100),
                            DateOfBirth = new DateTime(2019, 2, 15, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1099),
                            EnclosureId = -3,
                            Name = "animal_46",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -47,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1118),
                            DateOfBirth = new DateTime(2022, 2, 25, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1117),
                            EnclosureId = -5,
                            Name = "animal_47",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1137),
                            DateOfBirth = new DateTime(2022, 1, 6, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1136),
                            EnclosureId = -3,
                            Name = "animal_48",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -49,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1155),
                            DateOfBirth = new DateTime(2021, 2, 5, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1154),
                            EnclosureId = -2,
                            Name = "animal_49",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -50,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1188),
                            DateOfBirth = new DateTime(2021, 4, 15, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1187),
                            EnclosureId = -1,
                            Name = "animal_50",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1209),
                            DateOfBirth = new DateTime(2023, 12, 25, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1207),
                            EnclosureId = -3,
                            Name = "animal_51",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1227),
                            DateOfBirth = new DateTime(2022, 7, 10, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1226),
                            EnclosureId = -6,
                            Name = "animal_52",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -53,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1244),
                            DateOfBirth = new DateTime(2019, 3, 16, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1243),
                            EnclosureId = -6,
                            Name = "animal_53",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -54,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1263),
                            DateOfBirth = new DateTime(2018, 9, 28, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1261),
                            EnclosureId = -4,
                            Name = "animal_54",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -55,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1281),
                            DateOfBirth = new DateTime(2022, 11, 22, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1279),
                            EnclosureId = -6,
                            Name = "animal_55",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -56,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1299),
                            DateOfBirth = new DateTime(2021, 10, 29, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1297),
                            EnclosureId = -5,
                            Name = "animal_56",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -57,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1317),
                            DateOfBirth = new DateTime(2021, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1316),
                            EnclosureId = -5,
                            Name = "animal_57",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -58,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1336),
                            DateOfBirth = new DateTime(2021, 10, 30, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1335),
                            EnclosureId = -3,
                            Name = "animal_58",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -59,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1354),
                            DateOfBirth = new DateTime(2022, 10, 18, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1353),
                            EnclosureId = -4,
                            Name = "animal_59",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1432),
                            DateOfBirth = new DateTime(2016, 10, 20, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1430),
                            EnclosureId = -2,
                            Name = "animal_60",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1452),
                            DateOfBirth = new DateTime(2018, 12, 31, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1450),
                            EnclosureId = -2,
                            Name = "animal_61",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -62,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1470),
                            DateOfBirth = new DateTime(2016, 9, 25, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1469),
                            EnclosureId = -4,
                            Name = "animal_62",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -63,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1489),
                            DateOfBirth = new DateTime(2018, 5, 22, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1487),
                            EnclosureId = -1,
                            Name = "animal_63",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -64,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1507),
                            DateOfBirth = new DateTime(2021, 2, 24, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1505),
                            EnclosureId = -2,
                            Name = "animal_64",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -65,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1525),
                            DateOfBirth = new DateTime(2016, 10, 14, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1524),
                            EnclosureId = -3,
                            Name = "animal_65",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -66,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1543),
                            DateOfBirth = new DateTime(2016, 1, 1, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1542),
                            EnclosureId = -5,
                            Name = "animal_66",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -67,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1561),
                            DateOfBirth = new DateTime(2015, 12, 30, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1560),
                            EnclosureId = -6,
                            Name = "animal_67",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -68,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1580),
                            DateOfBirth = new DateTime(2016, 4, 21, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1579),
                            EnclosureId = -3,
                            Name = "animal_68",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -69,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1599),
                            DateOfBirth = new DateTime(2020, 5, 31, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1597),
                            EnclosureId = -4,
                            Name = "animal_69",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -70,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1632),
                            DateOfBirth = new DateTime(2020, 5, 3, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1631),
                            EnclosureId = -4,
                            Name = "animal_70",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1652),
                            DateOfBirth = new DateTime(2023, 12, 16, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1650),
                            EnclosureId = -2,
                            Name = "animal_71",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -72,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1670),
                            DateOfBirth = new DateTime(2019, 5, 10, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1668),
                            EnclosureId = -2,
                            Name = "animal_72",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1687),
                            DateOfBirth = new DateTime(2023, 8, 28, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1686),
                            EnclosureId = -2,
                            Name = "animal_73",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -74,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1705),
                            DateOfBirth = new DateTime(2017, 3, 1, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1703),
                            EnclosureId = -1,
                            Name = "animal_74",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -75,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1722),
                            DateOfBirth = new DateTime(2019, 8, 15, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1721),
                            EnclosureId = -1,
                            Name = "animal_75",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -76,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1741),
                            DateOfBirth = new DateTime(2022, 11, 2, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1739),
                            EnclosureId = -6,
                            Name = "animal_76",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -77,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1759),
                            DateOfBirth = new DateTime(2016, 10, 28, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1758),
                            EnclosureId = -2,
                            Name = "animal_77",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -78,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1777),
                            DateOfBirth = new DateTime(2017, 6, 25, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1776),
                            EnclosureId = -4,
                            Name = "animal_78",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1795),
                            DateOfBirth = new DateTime(2020, 6, 10, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1794),
                            EnclosureId = -6,
                            Name = "animal_79",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -80,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1828),
                            DateOfBirth = new DateTime(2021, 2, 21, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1826),
                            EnclosureId = -3,
                            Name = "animal_80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1886),
                            DateOfBirth = new DateTime(2020, 11, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1884),
                            EnclosureId = -4,
                            Name = "animal_81",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -82,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1905),
                            DateOfBirth = new DateTime(2022, 9, 17, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1904),
                            EnclosureId = -1,
                            Name = "animal_82",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -83,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1925),
                            DateOfBirth = new DateTime(2016, 4, 19, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1923),
                            EnclosureId = -1,
                            Name = "animal_83",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -84,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1943),
                            DateOfBirth = new DateTime(2023, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1942),
                            EnclosureId = -2,
                            Name = "animal_84",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -85,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1961),
                            DateOfBirth = new DateTime(2023, 8, 15, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1959),
                            EnclosureId = -3,
                            Name = "animal_85",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -86,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1979),
                            DateOfBirth = new DateTime(2023, 5, 29, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1977),
                            EnclosureId = -4,
                            Name = "animal_86",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -87,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(1997),
                            DateOfBirth = new DateTime(2020, 8, 15, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(1995),
                            EnclosureId = -2,
                            Name = "animal_87",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -88,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2015),
                            DateOfBirth = new DateTime(2017, 3, 27, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2013),
                            EnclosureId = -2,
                            Name = "animal_88",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -89,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2033),
                            DateOfBirth = new DateTime(2018, 10, 10, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2032),
                            EnclosureId = -1,
                            Name = "animal_89",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -90,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2068),
                            DateOfBirth = new DateTime(2016, 11, 28, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2066),
                            EnclosureId = -1,
                            Name = "animal_90",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2086),
                            DateOfBirth = new DateTime(2022, 5, 3, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2084),
                            EnclosureId = -3,
                            Name = "animal_91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -92,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2104),
                            DateOfBirth = new DateTime(2018, 12, 5, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2103),
                            EnclosureId = -2,
                            Name = "animal_92",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -93,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2122),
                            DateOfBirth = new DateTime(2023, 1, 18, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2120),
                            EnclosureId = -1,
                            Name = "animal_93",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -94,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2139),
                            DateOfBirth = new DateTime(2016, 1, 9, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2138),
                            EnclosureId = -2,
                            Name = "animal_94",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -95,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2157),
                            DateOfBirth = new DateTime(2019, 4, 13, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2156),
                            EnclosureId = -1,
                            Name = "animal_95",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -96,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2176),
                            DateOfBirth = new DateTime(2022, 11, 19, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2175),
                            EnclosureId = -2,
                            Name = "animal_96",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -97,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2194),
                            DateOfBirth = new DateTime(2019, 6, 22, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2193),
                            EnclosureId = -6,
                            Name = "animal_97",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -98,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2212),
                            DateOfBirth = new DateTime(2024, 1, 10, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2211),
                            EnclosureId = -1,
                            Name = "animal_98",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -99,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2229),
                            DateOfBirth = new DateTime(2018, 3, 25, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2228),
                            EnclosureId = -3,
                            Name = "animal_99",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -100,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2307),
                            DateOfBirth = new DateTime(2017, 4, 12, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2305),
                            EnclosureId = -1,
                            Name = "animal_100",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2327),
                            DateOfBirth = new DateTime(2024, 1, 23, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2325),
                            EnclosureId = -6,
                            Name = "animal_101",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -102,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2346),
                            DateOfBirth = new DateTime(2019, 10, 21, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2345),
                            EnclosureId = -1,
                            Name = "animal_102",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -103,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2364),
                            DateOfBirth = new DateTime(2017, 3, 14, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2363),
                            EnclosureId = -1,
                            Name = "animal_103",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -104,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2382),
                            DateOfBirth = new DateTime(2020, 6, 30, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2381),
                            EnclosureId = -3,
                            Name = "animal_104",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -105,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2400),
                            DateOfBirth = new DateTime(2022, 8, 5, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2399),
                            EnclosureId = -1,
                            Name = "animal_105",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -106,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2419),
                            DateOfBirth = new DateTime(2019, 10, 25, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2418),
                            EnclosureId = -1,
                            Name = "animal_106",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -107,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2438),
                            DateOfBirth = new DateTime(2019, 4, 11, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2437),
                            EnclosureId = -5,
                            Name = "animal_107",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -108,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2457),
                            DateOfBirth = new DateTime(2017, 6, 14, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2456),
                            EnclosureId = -4,
                            Name = "animal_108",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -109,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2475),
                            DateOfBirth = new DateTime(2019, 8, 8, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2474),
                            EnclosureId = -5,
                            Name = "animal_109",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -110,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2509),
                            DateOfBirth = new DateTime(2019, 4, 21, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2507),
                            EnclosureId = -5,
                            Name = "animal_110",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2527),
                            DateOfBirth = new DateTime(2023, 5, 18, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2526),
                            EnclosureId = -2,
                            Name = "animal_111",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -112,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2545),
                            DateOfBirth = new DateTime(2020, 11, 19, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2544),
                            EnclosureId = -5,
                            Name = "animal_112",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -113,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2564),
                            DateOfBirth = new DateTime(2016, 7, 7, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2562),
                            EnclosureId = -5,
                            Name = "animal_113",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -114,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2582),
                            DateOfBirth = new DateTime(2020, 2, 24, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2580),
                            EnclosureId = -6,
                            Name = "animal_114",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -115,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2600),
                            DateOfBirth = new DateTime(2018, 1, 18, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2599),
                            EnclosureId = -6,
                            Name = "animal_115",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -116,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2619),
                            DateOfBirth = new DateTime(2016, 2, 10, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2618),
                            EnclosureId = -3,
                            Name = "animal_116",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -117,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2637),
                            DateOfBirth = new DateTime(2019, 4, 29, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2636),
                            EnclosureId = -3,
                            Name = "animal_117",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -118,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2655),
                            DateOfBirth = new DateTime(2019, 2, 22, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2654),
                            EnclosureId = -2,
                            Name = "animal_118",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -119,
                            DateOfAquisition = new DateTime(2024, 3, 11, 22, 31, 21, 389, DateTimeKind.Utc).AddTicks(2673),
                            DateOfBirth = new DateTime(2020, 6, 4, 21, 31, 21, 389, DateTimeKind.Utc).AddTicks(2672),
                            EnclosureId = -5,
                            Name = "animal_119",
                            Sex = 1,
                            SpeciesId = -11
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Capacity = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = -2,
                            Capacity = 50,
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            Capacity = 40,
                            Type = 2
                        },
                        new
                        {
                            Id = -4,
                            Capacity = 6,
                            Type = 3
                        },
                        new
                        {
                            Id = -5,
                            Capacity = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = -6,
                            Capacity = 1000,
                            Type = 5
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 1,
                            Name = "species_2"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 5,
                            Name = "species_3"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 2,
                            Name = "species_4"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 2,
                            Name = "species_5"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 0,
                            Name = "species_6"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 3,
                            Name = "species_7"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 1,
                            Name = "species_8"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 0,
                            Name = "species_9"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 0,
                            Name = "species_10"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 3,
                            Name = "species_11"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
