// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240313142100_EnclosureOutOfConstructorRemoveHasMany")]
    partial class EnclosureOutOfConstructorRemoveHasMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -20,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3653),
                            DateOfBirth = new DateTime(2020, 5, 24, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(3643),
                            EnclosureId = -4,
                            Name = "animal_20",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3678),
                            DateOfBirth = new DateTime(2016, 6, 27, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(3676),
                            EnclosureId = -6,
                            Name = "animal_21",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -22,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3695),
                            DateOfBirth = new DateTime(2020, 3, 26, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3694),
                            EnclosureId = -2,
                            Name = "animal_22",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -23,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3714),
                            DateOfBirth = new DateTime(2023, 5, 18, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(3713),
                            EnclosureId = -5,
                            Name = "animal_23",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -24,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3732),
                            DateOfBirth = new DateTime(2017, 1, 1, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3730),
                            EnclosureId = -3,
                            Name = "animal_24",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -25,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3748),
                            DateOfBirth = new DateTime(2022, 11, 26, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3747),
                            EnclosureId = -1,
                            Name = "animal_25",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3766),
                            DateOfBirth = new DateTime(2018, 2, 24, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3764),
                            EnclosureId = -1,
                            Name = "animal_26",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -27,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3785),
                            DateOfBirth = new DateTime(2017, 10, 30, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3783),
                            EnclosureId = -4,
                            Name = "animal_27",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -28,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3802),
                            DateOfBirth = new DateTime(2021, 6, 4, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(3800),
                            EnclosureId = -1,
                            Name = "animal_28",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -29,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3874),
                            DateOfBirth = new DateTime(2019, 10, 2, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(3873),
                            EnclosureId = -1,
                            Name = "animal_29",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -30,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3909),
                            DateOfBirth = new DateTime(2016, 9, 17, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(3907),
                            EnclosureId = -5,
                            Name = "animal_30",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3927),
                            DateOfBirth = new DateTime(2022, 6, 18, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(3926),
                            EnclosureId = -3,
                            Name = "animal_31",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3944),
                            DateOfBirth = new DateTime(2018, 2, 24, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3943),
                            EnclosureId = -2,
                            Name = "animal_32",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -33,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3962),
                            DateOfBirth = new DateTime(2020, 12, 24, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3960),
                            EnclosureId = -1,
                            Name = "animal_33",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3979),
                            DateOfBirth = new DateTime(2022, 12, 22, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(3978),
                            EnclosureId = -4,
                            Name = "animal_34",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -35,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4003),
                            DateOfBirth = new DateTime(2024, 1, 17, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4002),
                            EnclosureId = -5,
                            Name = "animal_35",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -36,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4025),
                            DateOfBirth = new DateTime(2023, 1, 26, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4024),
                            EnclosureId = -2,
                            Name = "animal_36",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -37,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4043),
                            DateOfBirth = new DateTime(2023, 9, 6, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4041),
                            EnclosureId = -6,
                            Name = "animal_37",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -38,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4060),
                            DateOfBirth = new DateTime(2020, 3, 22, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4059),
                            EnclosureId = -3,
                            Name = "animal_38",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4077),
                            DateOfBirth = new DateTime(2021, 9, 30, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4075),
                            EnclosureId = -1,
                            Name = "animal_39",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4108),
                            DateOfBirth = new DateTime(2020, 2, 16, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4106),
                            EnclosureId = -2,
                            Name = "animal_40",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4125),
                            DateOfBirth = new DateTime(2020, 1, 30, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4124),
                            EnclosureId = -5,
                            Name = "animal_41",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -42,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4143),
                            DateOfBirth = new DateTime(2018, 11, 16, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4141),
                            EnclosureId = -6,
                            Name = "animal_42",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4160),
                            DateOfBirth = new DateTime(2022, 11, 24, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4159),
                            EnclosureId = -2,
                            Name = "animal_43",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -44,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4178),
                            DateOfBirth = new DateTime(2021, 2, 9, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4176),
                            EnclosureId = -1,
                            Name = "animal_44",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -45,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4195),
                            DateOfBirth = new DateTime(2024, 2, 6, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4194),
                            EnclosureId = -1,
                            Name = "animal_45",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -46,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4213),
                            DateOfBirth = new DateTime(2023, 8, 22, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4211),
                            EnclosureId = -3,
                            Name = "animal_46",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -47,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4230),
                            DateOfBirth = new DateTime(2017, 9, 7, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4229),
                            EnclosureId = -2,
                            Name = "animal_47",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4247),
                            DateOfBirth = new DateTime(2023, 8, 16, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4246),
                            EnclosureId = -1,
                            Name = "animal_48",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -49,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4265),
                            DateOfBirth = new DateTime(2023, 2, 1, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4264),
                            EnclosureId = -2,
                            Name = "animal_49",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -50,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4358),
                            DateOfBirth = new DateTime(2016, 2, 1, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4356),
                            EnclosureId = -5,
                            Name = "animal_50",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4378),
                            DateOfBirth = new DateTime(2018, 6, 26, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4377),
                            EnclosureId = -1,
                            Name = "animal_51",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4396),
                            DateOfBirth = new DateTime(2021, 4, 30, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4394),
                            EnclosureId = -5,
                            Name = "animal_52",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -53,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4413),
                            DateOfBirth = new DateTime(2021, 7, 13, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4411),
                            EnclosureId = -2,
                            Name = "animal_53",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -54,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4431),
                            DateOfBirth = new DateTime(2020, 1, 30, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4429),
                            EnclosureId = -2,
                            Name = "animal_54",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -55,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4448),
                            DateOfBirth = new DateTime(2018, 2, 24, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4447),
                            EnclosureId = -2,
                            Name = "animal_55",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -56,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4466),
                            DateOfBirth = new DateTime(2018, 8, 29, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4465),
                            EnclosureId = -3,
                            Name = "animal_56",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -57,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4484),
                            DateOfBirth = new DateTime(2019, 10, 26, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4482),
                            EnclosureId = -4,
                            Name = "animal_57",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -58,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4506),
                            DateOfBirth = new DateTime(2019, 3, 25, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4505),
                            EnclosureId = -6,
                            Name = "animal_58",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -59,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4524),
                            DateOfBirth = new DateTime(2023, 2, 23, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4522),
                            EnclosureId = -1,
                            Name = "animal_59",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4556),
                            DateOfBirth = new DateTime(2019, 8, 4, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4554),
                            EnclosureId = -5,
                            Name = "animal_60",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4574),
                            DateOfBirth = new DateTime(2022, 7, 11, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4573),
                            EnclosureId = -6,
                            Name = "animal_61",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -62,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4592),
                            DateOfBirth = new DateTime(2023, 2, 6, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4591),
                            EnclosureId = -2,
                            Name = "animal_62",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -63,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4610),
                            DateOfBirth = new DateTime(2020, 4, 2, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4609),
                            EnclosureId = -1,
                            Name = "animal_63",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -64,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4627),
                            DateOfBirth = new DateTime(2023, 5, 12, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4626),
                            EnclosureId = -2,
                            Name = "animal_64",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -65,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4645),
                            DateOfBirth = new DateTime(2020, 6, 23, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4643),
                            EnclosureId = -5,
                            Name = "animal_65",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -66,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4662),
                            DateOfBirth = new DateTime(2023, 1, 17, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4661),
                            EnclosureId = -5,
                            Name = "animal_66",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -67,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4679),
                            DateOfBirth = new DateTime(2020, 7, 27, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4678),
                            EnclosureId = -4,
                            Name = "animal_67",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -68,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4697),
                            DateOfBirth = new DateTime(2020, 11, 12, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4696),
                            EnclosureId = -3,
                            Name = "animal_68",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -69,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4715),
                            DateOfBirth = new DateTime(2023, 11, 18, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4713),
                            EnclosureId = -5,
                            Name = "animal_69",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -70,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4789),
                            DateOfBirth = new DateTime(2021, 5, 20, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4787),
                            EnclosureId = -3,
                            Name = "animal_70",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4808),
                            DateOfBirth = new DateTime(2021, 10, 16, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4806),
                            EnclosureId = -6,
                            Name = "animal_71",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -72,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4826),
                            DateOfBirth = new DateTime(2023, 2, 27, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4825),
                            EnclosureId = -4,
                            Name = "animal_72",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4844),
                            DateOfBirth = new DateTime(2023, 10, 29, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4842),
                            EnclosureId = -1,
                            Name = "animal_73",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -74,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4863),
                            DateOfBirth = new DateTime(2017, 1, 19, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4862),
                            EnclosureId = -1,
                            Name = "animal_74",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -75,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4880),
                            DateOfBirth = new DateTime(2022, 2, 2, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4879),
                            EnclosureId = -3,
                            Name = "animal_75",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -76,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4897),
                            DateOfBirth = new DateTime(2020, 2, 8, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4896),
                            EnclosureId = -1,
                            Name = "animal_76",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -77,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4914),
                            DateOfBirth = new DateTime(2019, 6, 23, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4913),
                            EnclosureId = -6,
                            Name = "animal_77",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -78,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4932),
                            DateOfBirth = new DateTime(2019, 8, 4, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4931),
                            EnclosureId = -6,
                            Name = "animal_78",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4949),
                            DateOfBirth = new DateTime(2022, 12, 24, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4948),
                            EnclosureId = -5,
                            Name = "animal_79",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -80,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4979),
                            DateOfBirth = new DateTime(2024, 3, 3, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4978),
                            EnclosureId = -6,
                            Name = "animal_80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(4997),
                            DateOfBirth = new DateTime(2017, 4, 5, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(4996),
                            EnclosureId = -4,
                            Name = "animal_81",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -82,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5015),
                            DateOfBirth = new DateTime(2016, 12, 15, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5013),
                            EnclosureId = -4,
                            Name = "animal_82",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -83,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5034),
                            DateOfBirth = new DateTime(2021, 1, 21, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5032),
                            EnclosureId = -3,
                            Name = "animal_83",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -84,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5052),
                            DateOfBirth = new DateTime(2019, 7, 8, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5051),
                            EnclosureId = -2,
                            Name = "animal_84",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -85,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5070),
                            DateOfBirth = new DateTime(2021, 4, 10, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5068),
                            EnclosureId = -6,
                            Name = "animal_85",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -86,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5087),
                            DateOfBirth = new DateTime(2023, 11, 28, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5086),
                            EnclosureId = -5,
                            Name = "animal_86",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -87,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5105),
                            DateOfBirth = new DateTime(2017, 2, 19, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5103),
                            EnclosureId = -3,
                            Name = "animal_87",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -88,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5122),
                            DateOfBirth = new DateTime(2016, 5, 14, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5121),
                            EnclosureId = -2,
                            Name = "animal_88",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -89,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5182),
                            DateOfBirth = new DateTime(2020, 4, 18, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5181),
                            EnclosureId = -3,
                            Name = "animal_89",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -90,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5219),
                            DateOfBirth = new DateTime(2022, 12, 29, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5218),
                            EnclosureId = -6,
                            Name = "animal_90",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5238),
                            DateOfBirth = new DateTime(2022, 10, 26, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5236),
                            EnclosureId = -6,
                            Name = "animal_91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -92,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5256),
                            DateOfBirth = new DateTime(2019, 10, 8, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5255),
                            EnclosureId = -6,
                            Name = "animal_92",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -93,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5274),
                            DateOfBirth = new DateTime(2016, 7, 30, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5272),
                            EnclosureId = -6,
                            Name = "animal_93",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -94,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5291),
                            DateOfBirth = new DateTime(2018, 9, 4, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5290),
                            EnclosureId = -6,
                            Name = "animal_94",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -95,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5309),
                            DateOfBirth = new DateTime(2020, 7, 1, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5307),
                            EnclosureId = -3,
                            Name = "animal_95",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -96,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5326),
                            DateOfBirth = new DateTime(2020, 11, 14, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5324),
                            EnclosureId = -6,
                            Name = "animal_96",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -97,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5343),
                            DateOfBirth = new DateTime(2017, 11, 19, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5342),
                            EnclosureId = -3,
                            Name = "animal_97",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -98,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5361),
                            DateOfBirth = new DateTime(2022, 11, 8, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5360),
                            EnclosureId = -2,
                            Name = "animal_98",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -99,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5379),
                            DateOfBirth = new DateTime(2016, 12, 26, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5377),
                            EnclosureId = -5,
                            Name = "animal_99",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -100,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5411),
                            DateOfBirth = new DateTime(2021, 9, 11, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5409),
                            EnclosureId = -6,
                            Name = "animal_100",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5429),
                            DateOfBirth = new DateTime(2022, 6, 24, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5428),
                            EnclosureId = -2,
                            Name = "animal_101",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -102,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5447),
                            DateOfBirth = new DateTime(2018, 7, 30, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5446),
                            EnclosureId = -1,
                            Name = "animal_102",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -103,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5465),
                            DateOfBirth = new DateTime(2016, 8, 11, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5464),
                            EnclosureId = -3,
                            Name = "animal_103",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -104,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5482),
                            DateOfBirth = new DateTime(2016, 1, 27, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5481),
                            EnclosureId = -1,
                            Name = "animal_104",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -105,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5500),
                            DateOfBirth = new DateTime(2021, 12, 29, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5499),
                            EnclosureId = -6,
                            Name = "animal_105",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -106,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5518),
                            DateOfBirth = new DateTime(2016, 11, 2, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5516),
                            EnclosureId = -2,
                            Name = "animal_106",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -107,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5535),
                            DateOfBirth = new DateTime(2022, 8, 18, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5534),
                            EnclosureId = -1,
                            Name = "animal_107",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -108,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5553),
                            DateOfBirth = new DateTime(2022, 12, 8, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5551),
                            EnclosureId = -1,
                            Name = "animal_108",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -109,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5570),
                            DateOfBirth = new DateTime(2018, 9, 2, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5568),
                            EnclosureId = -1,
                            Name = "animal_109",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -110,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5644),
                            DateOfBirth = new DateTime(2019, 1, 23, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5642),
                            EnclosureId = -2,
                            Name = "animal_110",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5662),
                            DateOfBirth = new DateTime(2023, 2, 28, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5661),
                            EnclosureId = -5,
                            Name = "animal_111",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -112,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5679),
                            DateOfBirth = new DateTime(2021, 10, 7, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5678),
                            EnclosureId = -4,
                            Name = "animal_112",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -113,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5697),
                            DateOfBirth = new DateTime(2023, 8, 20, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5695),
                            EnclosureId = -5,
                            Name = "animal_113",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -114,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5714),
                            DateOfBirth = new DateTime(2016, 2, 14, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5712),
                            EnclosureId = -6,
                            Name = "animal_114",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -115,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5732),
                            DateOfBirth = new DateTime(2016, 5, 14, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5730),
                            EnclosureId = -3,
                            Name = "animal_115",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -116,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5749),
                            DateOfBirth = new DateTime(2018, 2, 7, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5748),
                            EnclosureId = -5,
                            Name = "animal_116",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -117,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5766),
                            DateOfBirth = new DateTime(2022, 1, 12, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5765),
                            EnclosureId = -1,
                            Name = "animal_117",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -118,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5783),
                            DateOfBirth = new DateTime(2017, 5, 5, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5782),
                            EnclosureId = -5,
                            Name = "animal_118",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -119,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 20, 59, 760, DateTimeKind.Utc).AddTicks(5801),
                            DateOfBirth = new DateTime(2017, 10, 7, 13, 20, 59, 760, DateTimeKind.Utc).AddTicks(5800),
                            EnclosureId = -6,
                            Name = "animal_119",
                            Sex = 0,
                            SpeciesId = -11
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Capacity = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = -2,
                            Capacity = 50,
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            Capacity = 40,
                            Type = 2
                        },
                        new
                        {
                            Id = -4,
                            Capacity = 6,
                            Type = 3
                        },
                        new
                        {
                            Id = -5,
                            Capacity = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = -6,
                            Capacity = 1000,
                            Type = 5
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 5,
                            Name = "species_2"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 3,
                            Name = "species_3"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 3,
                            Name = "species_4"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 3,
                            Name = "species_5"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 2,
                            Name = "species_6"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 4,
                            Name = "species_7"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 4,
                            Name = "species_8"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 1,
                            Name = "species_9"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 5,
                            Name = "species_10"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 1,
                            Name = "species_11"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
