// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240306153501_SeedDataRandomBirth")]
    partial class SeedDataRandomBirth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -20,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3899),
                            DateOfBirth = new DateTime(2019, 11, 3, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3875),
                            Name = "animal_20",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3921),
                            DateOfBirth = new DateTime(2018, 1, 2, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3919),
                            Name = "animal_21",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -22,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3938),
                            DateOfBirth = new DateTime(2021, 2, 19, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3937),
                            Name = "animal_22",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -23,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3958),
                            DateOfBirth = new DateTime(2021, 2, 11, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3956),
                            Name = "animal_23",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -24,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3974),
                            DateOfBirth = new DateTime(2022, 12, 3, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3973),
                            Name = "animal_24",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -25,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(3991),
                            DateOfBirth = new DateTime(2021, 6, 4, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(3989),
                            Name = "animal_25",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4009),
                            DateOfBirth = new DateTime(2017, 10, 10, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4008),
                            Name = "animal_26",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -27,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4027),
                            DateOfBirth = new DateTime(2019, 1, 3, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4026),
                            Name = "animal_27",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -28,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4044),
                            DateOfBirth = new DateTime(2017, 11, 1, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4043),
                            Name = "animal_28",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -29,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4060),
                            DateOfBirth = new DateTime(2022, 5, 12, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4059),
                            Name = "animal_29",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -30,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4101),
                            DateOfBirth = new DateTime(2024, 2, 17, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4099),
                            Name = "animal_30",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4117),
                            DateOfBirth = new DateTime(2023, 11, 30, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4116),
                            Name = "animal_31",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4138),
                            DateOfBirth = new DateTime(2023, 3, 3, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4137),
                            Name = "animal_32",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -33,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4214),
                            DateOfBirth = new DateTime(2022, 2, 22, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4212),
                            Name = "animal_33",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4231),
                            DateOfBirth = new DateTime(2019, 11, 18, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4229),
                            Name = "animal_34",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -35,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4250),
                            DateOfBirth = new DateTime(2019, 9, 27, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4248),
                            Name = "animal_35",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -36,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4267),
                            DateOfBirth = new DateTime(2017, 1, 5, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4266),
                            Name = "animal_36",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -37,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4284),
                            DateOfBirth = new DateTime(2017, 2, 12, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4282),
                            Name = "animal_37",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -38,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4300),
                            DateOfBirth = new DateTime(2022, 6, 6, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4299),
                            Name = "animal_38",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4317),
                            DateOfBirth = new DateTime(2019, 11, 19, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4316),
                            Name = "animal_39",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4349),
                            DateOfBirth = new DateTime(2018, 11, 12, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4347),
                            Name = "animal_40",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4366),
                            DateOfBirth = new DateTime(2018, 12, 20, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4364),
                            Name = "animal_41",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -42,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4382),
                            DateOfBirth = new DateTime(2021, 9, 19, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4381),
                            Name = "animal_42",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4398),
                            DateOfBirth = new DateTime(2018, 2, 5, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4397),
                            Name = "animal_43",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -44,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4415),
                            DateOfBirth = new DateTime(2019, 3, 23, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4413),
                            Name = "animal_44",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -45,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4431),
                            DateOfBirth = new DateTime(2020, 8, 9, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4430),
                            Name = "animal_45",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -46,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4449),
                            DateOfBirth = new DateTime(2022, 2, 5, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4447),
                            Name = "animal_46",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -47,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4464),
                            DateOfBirth = new DateTime(2023, 7, 14, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4463),
                            Name = "animal_47",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4481),
                            DateOfBirth = new DateTime(2020, 6, 19, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4480),
                            Name = "animal_48",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -49,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4499),
                            DateOfBirth = new DateTime(2019, 9, 20, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4497),
                            Name = "animal_49",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -50,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4532),
                            DateOfBirth = new DateTime(2018, 9, 15, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4530),
                            Name = "animal_50",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4551),
                            DateOfBirth = new DateTime(2017, 9, 20, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4549),
                            Name = "animal_51",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4620),
                            DateOfBirth = new DateTime(2016, 11, 1, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4619),
                            Name = "animal_52",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -53,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4657),
                            DateOfBirth = new DateTime(2021, 1, 28, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4655),
                            Name = "animal_53",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -54,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4688),
                            DateOfBirth = new DateTime(2020, 11, 1, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4687),
                            Name = "animal_54",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -55,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4704),
                            DateOfBirth = new DateTime(2017, 8, 23, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4702),
                            Name = "animal_55",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -56,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4720),
                            DateOfBirth = new DateTime(2021, 8, 9, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4719),
                            Name = "animal_56",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -57,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4737),
                            DateOfBirth = new DateTime(2023, 12, 30, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4735),
                            Name = "animal_57",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -58,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4753),
                            DateOfBirth = new DateTime(2017, 6, 5, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4752),
                            Name = "animal_58",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -59,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4770),
                            DateOfBirth = new DateTime(2018, 7, 24, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4768),
                            Name = "animal_59",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4801),
                            DateOfBirth = new DateTime(2021, 5, 12, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4800),
                            Name = "animal_60",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4818),
                            DateOfBirth = new DateTime(2018, 4, 26, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4817),
                            Name = "animal_61",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -62,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(4835),
                            DateOfBirth = new DateTime(2016, 6, 1, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(4833),
                            Name = "animal_62",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -63,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5045),
                            DateOfBirth = new DateTime(2019, 9, 5, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5044),
                            Name = "animal_63",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -64,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5065),
                            DateOfBirth = new DateTime(2022, 4, 29, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5063),
                            Name = "animal_64",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -65,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5082),
                            DateOfBirth = new DateTime(2022, 5, 18, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5081),
                            Name = "animal_65",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -66,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5101),
                            DateOfBirth = new DateTime(2017, 3, 29, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5100),
                            Name = "animal_66",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -67,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5119),
                            DateOfBirth = new DateTime(2016, 2, 5, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5117),
                            Name = "animal_67",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -68,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5138),
                            DateOfBirth = new DateTime(2020, 3, 11, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5136),
                            Name = "animal_68",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -69,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5295),
                            DateOfBirth = new DateTime(2021, 9, 16, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5291),
                            Name = "animal_69",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -70,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5332),
                            DateOfBirth = new DateTime(2020, 9, 21, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5330),
                            Name = "animal_70",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5349),
                            DateOfBirth = new DateTime(2017, 7, 17, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5348),
                            Name = "animal_71",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -72,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5366),
                            DateOfBirth = new DateTime(2023, 12, 13, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5364),
                            Name = "animal_72",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5382),
                            DateOfBirth = new DateTime(2022, 10, 23, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5381),
                            Name = "animal_73",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -74,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5479),
                            DateOfBirth = new DateTime(2021, 5, 24, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5477),
                            Name = "animal_74",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -75,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5497),
                            DateOfBirth = new DateTime(2019, 4, 5, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5496),
                            Name = "animal_75",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -76,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5515),
                            DateOfBirth = new DateTime(2016, 5, 28, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5513),
                            Name = "animal_76",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -77,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5532),
                            DateOfBirth = new DateTime(2017, 11, 18, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5531),
                            Name = "animal_77",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -78,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5549),
                            DateOfBirth = new DateTime(2021, 2, 16, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5548),
                            Name = "animal_78",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5566),
                            DateOfBirth = new DateTime(2018, 1, 14, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5564),
                            Name = "animal_79",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -80,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5600),
                            DateOfBirth = new DateTime(2021, 11, 10, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5598),
                            Name = "animal_80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5617),
                            DateOfBirth = new DateTime(2023, 7, 2, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5616),
                            Name = "animal_81",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -82,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5634),
                            DateOfBirth = new DateTime(2021, 6, 1, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5633),
                            Name = "animal_82",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -83,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5654),
                            DateOfBirth = new DateTime(2022, 8, 3, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5653),
                            Name = "animal_83",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -84,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5671),
                            DateOfBirth = new DateTime(2015, 12, 28, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5670),
                            Name = "animal_84",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -85,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5688),
                            DateOfBirth = new DateTime(2021, 12, 31, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5687),
                            Name = "animal_85",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -86,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5706),
                            DateOfBirth = new DateTime(2022, 10, 2, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5704),
                            Name = "animal_86",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -87,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5723),
                            DateOfBirth = new DateTime(2018, 6, 8, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5722),
                            Name = "animal_87",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -88,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5740),
                            DateOfBirth = new DateTime(2023, 11, 11, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5739),
                            Name = "animal_88",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -89,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5757),
                            DateOfBirth = new DateTime(2023, 5, 19, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5755),
                            Name = "animal_89",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -90,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5789),
                            DateOfBirth = new DateTime(2024, 2, 19, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5788),
                            Name = "animal_90",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5806),
                            DateOfBirth = new DateTime(2022, 8, 8, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5805),
                            Name = "animal_91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -92,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5883),
                            DateOfBirth = new DateTime(2020, 11, 9, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5881),
                            Name = "animal_92",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -93,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5902),
                            DateOfBirth = new DateTime(2023, 4, 4, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5900),
                            Name = "animal_93",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -94,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5919),
                            DateOfBirth = new DateTime(2019, 7, 23, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5917),
                            Name = "animal_94",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -95,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5935),
                            DateOfBirth = new DateTime(2017, 8, 28, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5934),
                            Name = "animal_95",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -96,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5952),
                            DateOfBirth = new DateTime(2018, 12, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5951),
                            Name = "animal_96",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -97,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5969),
                            DateOfBirth = new DateTime(2017, 4, 18, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5968),
                            Name = "animal_97",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -98,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(5987),
                            DateOfBirth = new DateTime(2023, 3, 28, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(5985),
                            Name = "animal_98",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -99,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6003),
                            DateOfBirth = new DateTime(2019, 7, 1, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6002),
                            Name = "animal_99",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -100,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6037),
                            DateOfBirth = new DateTime(2021, 6, 3, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6035),
                            Name = "animal_100",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6055),
                            DateOfBirth = new DateTime(2016, 9, 22, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6054),
                            Name = "animal_101",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -102,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6073),
                            DateOfBirth = new DateTime(2023, 9, 18, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6071),
                            Name = "animal_102",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -103,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6091),
                            DateOfBirth = new DateTime(2021, 6, 27, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6089),
                            Name = "animal_103",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -104,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6108),
                            DateOfBirth = new DateTime(2019, 4, 25, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6107),
                            Name = "animal_104",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -105,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6125),
                            DateOfBirth = new DateTime(2019, 1, 22, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6124),
                            Name = "animal_105",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -106,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6141),
                            DateOfBirth = new DateTime(2019, 2, 8, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6140),
                            Name = "animal_106",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -107,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6158),
                            DateOfBirth = new DateTime(2019, 5, 28, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6157),
                            Name = "animal_107",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -108,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6176),
                            DateOfBirth = new DateTime(2022, 4, 5, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6174),
                            Name = "animal_108",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -109,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6193),
                            DateOfBirth = new DateTime(2016, 5, 12, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6191),
                            Name = "animal_109",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -110,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6228),
                            DateOfBirth = new DateTime(2021, 1, 20, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6226),
                            Name = "animal_110",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6246),
                            DateOfBirth = new DateTime(2021, 2, 25, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6244),
                            Name = "animal_111",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -112,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6263),
                            DateOfBirth = new DateTime(2017, 9, 23, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6262),
                            Name = "animal_112",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -113,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6281),
                            DateOfBirth = new DateTime(2023, 11, 3, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6279),
                            Name = "animal_113",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -114,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6340),
                            DateOfBirth = new DateTime(2023, 8, 21, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6339),
                            Name = "animal_114",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -115,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6359),
                            DateOfBirth = new DateTime(2022, 9, 30, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6358),
                            Name = "animal_115",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -116,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6376),
                            DateOfBirth = new DateTime(2020, 8, 9, 14, 35, 1, 272, DateTimeKind.Utc).AddTicks(6375),
                            Name = "animal_116",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -117,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6393),
                            DateOfBirth = new DateTime(2017, 11, 20, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6392),
                            Name = "animal_117",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -118,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6410),
                            DateOfBirth = new DateTime(2023, 2, 4, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6409),
                            Name = "animal_118",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -119,
                            DateOfAquisition = new DateTime(2024, 3, 6, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6428),
                            DateOfBirth = new DateTime(2020, 3, 7, 15, 35, 1, 272, DateTimeKind.Utc).AddTicks(6427),
                            Name = "animal_119",
                            Sex = 0,
                            SpeciesId = -11
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 1,
                            Name = "species_2"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 5,
                            Name = "species_3"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 0,
                            Name = "species_4"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 4,
                            Name = "species_5"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 4,
                            Name = "species_6"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 2,
                            Name = "species_7"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 2,
                            Name = "species_8"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 4,
                            Name = "species_9"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 2,
                            Name = "species_10"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 0,
                            Name = "species_11"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
