// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240313104250_EnclosureTest")]
    partial class EnclosureTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -20,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7795),
                            DateOfBirth = new DateTime(2021, 7, 29, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(7778),
                            EnclosureId = -1,
                            Name = "animal_20",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7827),
                            DateOfBirth = new DateTime(2019, 6, 21, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(7825),
                            EnclosureId = -1,
                            Name = "animal_21",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -22,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7848),
                            DateOfBirth = new DateTime(2021, 6, 6, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(7847),
                            EnclosureId = -1,
                            Name = "animal_22",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -23,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7876),
                            DateOfBirth = new DateTime(2017, 4, 24, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(7874),
                            EnclosureId = -1,
                            Name = "animal_23",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -24,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7898),
                            DateOfBirth = new DateTime(2019, 11, 7, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7896),
                            EnclosureId = -1,
                            Name = "animal_24",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -25,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7919),
                            DateOfBirth = new DateTime(2021, 7, 14, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(7917),
                            EnclosureId = -1,
                            Name = "animal_25",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7939),
                            DateOfBirth = new DateTime(2018, 9, 7, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(7937),
                            EnclosureId = -1,
                            Name = "animal_26",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -27,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7960),
                            DateOfBirth = new DateTime(2016, 8, 6, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(7959),
                            EnclosureId = -1,
                            Name = "animal_27",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -28,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7982),
                            DateOfBirth = new DateTime(2017, 12, 12, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(7981),
                            EnclosureId = -1,
                            Name = "animal_28",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -29,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8069),
                            DateOfBirth = new DateTime(2021, 3, 14, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8067),
                            EnclosureId = -1,
                            Name = "animal_29",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -30,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8108),
                            DateOfBirth = new DateTime(2018, 4, 8, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8106),
                            EnclosureId = -1,
                            Name = "animal_30",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8127),
                            DateOfBirth = new DateTime(2019, 5, 25, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8126),
                            EnclosureId = -1,
                            Name = "animal_31",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8148),
                            DateOfBirth = new DateTime(2021, 2, 28, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8146),
                            EnclosureId = -1,
                            Name = "animal_32",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -33,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8167),
                            DateOfBirth = new DateTime(2023, 6, 15, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8165),
                            EnclosureId = -1,
                            Name = "animal_33",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8186),
                            DateOfBirth = new DateTime(2021, 10, 8, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8185),
                            EnclosureId = -1,
                            Name = "animal_34",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -35,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8209),
                            DateOfBirth = new DateTime(2021, 6, 12, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8207),
                            EnclosureId = -1,
                            Name = "animal_35",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -36,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8230),
                            DateOfBirth = new DateTime(2020, 2, 14, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8228),
                            EnclosureId = -1,
                            Name = "animal_36",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -37,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8250),
                            DateOfBirth = new DateTime(2019, 12, 6, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8248),
                            EnclosureId = -1,
                            Name = "animal_37",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -38,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8270),
                            DateOfBirth = new DateTime(2022, 5, 10, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8268),
                            EnclosureId = -1,
                            Name = "animal_38",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8290),
                            DateOfBirth = new DateTime(2019, 6, 17, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8289),
                            EnclosureId = -1,
                            Name = "animal_39",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8327),
                            DateOfBirth = new DateTime(2021, 5, 24, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8326),
                            EnclosureId = -1,
                            Name = "animal_40",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8348),
                            DateOfBirth = new DateTime(2016, 6, 23, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8346),
                            EnclosureId = -1,
                            Name = "animal_41",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -42,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8368),
                            DateOfBirth = new DateTime(2017, 7, 19, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8366),
                            EnclosureId = -1,
                            Name = "animal_42",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8388),
                            DateOfBirth = new DateTime(2019, 1, 11, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8386),
                            EnclosureId = -1,
                            Name = "animal_43",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -44,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8408),
                            DateOfBirth = new DateTime(2023, 1, 16, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8406),
                            EnclosureId = -1,
                            Name = "animal_44",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -45,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8428),
                            DateOfBirth = new DateTime(2021, 9, 6, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8426),
                            EnclosureId = -1,
                            Name = "animal_45",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -46,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8448),
                            DateOfBirth = new DateTime(2016, 4, 24, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8447),
                            EnclosureId = -1,
                            Name = "animal_46",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -47,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8469),
                            DateOfBirth = new DateTime(2020, 2, 24, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8467),
                            EnclosureId = -1,
                            Name = "animal_47",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8489),
                            DateOfBirth = new DateTime(2022, 4, 13, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8488),
                            EnclosureId = -1,
                            Name = "animal_48",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -49,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8509),
                            DateOfBirth = new DateTime(2022, 5, 12, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8508),
                            EnclosureId = -1,
                            Name = "animal_49",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -50,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8615),
                            DateOfBirth = new DateTime(2020, 5, 1, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8613),
                            EnclosureId = -1,
                            Name = "animal_50",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8637),
                            DateOfBirth = new DateTime(2018, 9, 23, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8636),
                            EnclosureId = -1,
                            Name = "animal_51",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8815),
                            DateOfBirth = new DateTime(2022, 2, 7, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8814),
                            EnclosureId = -1,
                            Name = "animal_52",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -53,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8836),
                            DateOfBirth = new DateTime(2023, 1, 4, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8834),
                            EnclosureId = -1,
                            Name = "animal_53",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -54,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8857),
                            DateOfBirth = new DateTime(2019, 8, 4, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8856),
                            EnclosureId = -1,
                            Name = "animal_54",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -55,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(8878),
                            DateOfBirth = new DateTime(2022, 10, 10, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(8876),
                            EnclosureId = -1,
                            Name = "animal_55",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -56,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9048),
                            DateOfBirth = new DateTime(2022, 6, 10, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9046),
                            EnclosureId = -1,
                            Name = "animal_56",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -57,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9069),
                            DateOfBirth = new DateTime(2022, 6, 13, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9067),
                            EnclosureId = -1,
                            Name = "animal_57",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -58,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9089),
                            DateOfBirth = new DateTime(2017, 5, 8, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9088),
                            EnclosureId = -1,
                            Name = "animal_58",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -59,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9109),
                            DateOfBirth = new DateTime(2016, 3, 23, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9108),
                            EnclosureId = -1,
                            Name = "animal_59",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9147),
                            DateOfBirth = new DateTime(2022, 1, 6, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9146),
                            EnclosureId = -1,
                            Name = "animal_60",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9168),
                            DateOfBirth = new DateTime(2022, 10, 17, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9167),
                            EnclosureId = -1,
                            Name = "animal_61",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -62,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9189),
                            DateOfBirth = new DateTime(2019, 1, 22, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9187),
                            EnclosureId = -1,
                            Name = "animal_62",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -63,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9210),
                            DateOfBirth = new DateTime(2024, 3, 12, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9208),
                            EnclosureId = -1,
                            Name = "animal_63",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -64,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9230),
                            DateOfBirth = new DateTime(2019, 5, 19, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9228),
                            EnclosureId = -1,
                            Name = "animal_64",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -65,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9250),
                            DateOfBirth = new DateTime(2016, 3, 16, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9248),
                            EnclosureId = -1,
                            Name = "animal_65",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -66,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9270),
                            DateOfBirth = new DateTime(2017, 1, 1, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9269),
                            EnclosureId = -1,
                            Name = "animal_66",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -67,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9291),
                            DateOfBirth = new DateTime(2021, 5, 10, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9290),
                            EnclosureId = -1,
                            Name = "animal_67",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -68,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9312),
                            DateOfBirth = new DateTime(2020, 6, 21, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9310),
                            EnclosureId = -1,
                            Name = "animal_68",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -69,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9464),
                            DateOfBirth = new DateTime(2018, 5, 18, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9462),
                            EnclosureId = -1,
                            Name = "animal_69",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -70,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9508),
                            DateOfBirth = new DateTime(2019, 12, 7, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9506),
                            EnclosureId = -1,
                            Name = "animal_70",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9529),
                            DateOfBirth = new DateTime(2022, 10, 16, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9528),
                            EnclosureId = -1,
                            Name = "animal_71",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -72,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9550),
                            DateOfBirth = new DateTime(2016, 10, 4, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9548),
                            EnclosureId = -1,
                            Name = "animal_72",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9570),
                            DateOfBirth = new DateTime(2021, 11, 17, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9568),
                            EnclosureId = -1,
                            Name = "animal_73",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -74,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9590),
                            DateOfBirth = new DateTime(2020, 2, 4, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9588),
                            EnclosureId = -1,
                            Name = "animal_74",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -75,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9610),
                            DateOfBirth = new DateTime(2023, 4, 22, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9608),
                            EnclosureId = -1,
                            Name = "animal_75",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -76,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9630),
                            DateOfBirth = new DateTime(2021, 5, 20, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9629),
                            EnclosureId = -1,
                            Name = "animal_76",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -77,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9651),
                            DateOfBirth = new DateTime(2018, 12, 1, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9649),
                            EnclosureId = -1,
                            Name = "animal_77",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -78,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9672),
                            DateOfBirth = new DateTime(2022, 4, 15, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9670),
                            EnclosureId = -1,
                            Name = "animal_78",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9692),
                            DateOfBirth = new DateTime(2023, 1, 1, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9690),
                            EnclosureId = -1,
                            Name = "animal_79",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -80,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9728),
                            DateOfBirth = new DateTime(2022, 8, 30, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9727),
                            EnclosureId = -1,
                            Name = "animal_80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9749),
                            DateOfBirth = new DateTime(2017, 8, 11, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9747),
                            EnclosureId = -1,
                            Name = "animal_81",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -82,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9769),
                            DateOfBirth = new DateTime(2017, 3, 14, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9768),
                            EnclosureId = -1,
                            Name = "animal_82",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -83,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9792),
                            DateOfBirth = new DateTime(2017, 2, 20, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9791),
                            EnclosureId = -1,
                            Name = "animal_83",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -84,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9813),
                            DateOfBirth = new DateTime(2018, 11, 26, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9811),
                            EnclosureId = -1,
                            Name = "animal_84",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -85,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9833),
                            DateOfBirth = new DateTime(2023, 12, 30, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9831),
                            EnclosureId = -1,
                            Name = "animal_85",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -86,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9853),
                            DateOfBirth = new DateTime(2019, 12, 9, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9851),
                            EnclosureId = -1,
                            Name = "animal_86",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -87,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9873),
                            DateOfBirth = new DateTime(2023, 2, 22, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9872),
                            EnclosureId = -1,
                            Name = "animal_87",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -88,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9942),
                            DateOfBirth = new DateTime(2020, 8, 11, 9, 42, 49, 916, DateTimeKind.Utc).AddTicks(9940),
                            EnclosureId = -1,
                            Name = "animal_88",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -89,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9963),
                            DateOfBirth = new DateTime(2024, 2, 21, 10, 42, 49, 916, DateTimeKind.Utc).AddTicks(9962),
                            EnclosureId = -1,
                            Name = "animal_89",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -90,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(5),
                            DateOfBirth = new DateTime(2018, 3, 14, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(4),
                            EnclosureId = -1,
                            Name = "animal_90",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(28),
                            DateOfBirth = new DateTime(2023, 11, 6, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(26),
                            EnclosureId = -1,
                            Name = "animal_91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -92,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(49),
                            DateOfBirth = new DateTime(2020, 5, 26, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(47),
                            EnclosureId = -1,
                            Name = "animal_92",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -93,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(69),
                            DateOfBirth = new DateTime(2016, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(67),
                            EnclosureId = -1,
                            Name = "animal_93",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -94,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(90),
                            DateOfBirth = new DateTime(2016, 6, 10, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(89),
                            EnclosureId = -1,
                            Name = "animal_94",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -95,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(111),
                            DateOfBirth = new DateTime(2019, 1, 27, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(109),
                            EnclosureId = -1,
                            Name = "animal_95",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -96,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(131),
                            DateOfBirth = new DateTime(2023, 11, 10, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(129),
                            EnclosureId = -1,
                            Name = "animal_96",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -97,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(151),
                            DateOfBirth = new DateTime(2022, 4, 21, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(150),
                            EnclosureId = -1,
                            Name = "animal_97",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -98,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(171),
                            DateOfBirth = new DateTime(2023, 3, 12, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(170),
                            EnclosureId = -1,
                            Name = "animal_98",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -99,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(192),
                            DateOfBirth = new DateTime(2021, 6, 15, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(190),
                            EnclosureId = -1,
                            Name = "animal_99",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -100,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(230),
                            DateOfBirth = new DateTime(2018, 11, 9, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(228),
                            EnclosureId = -1,
                            Name = "animal_100",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(250),
                            DateOfBirth = new DateTime(2016, 8, 19, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(249),
                            EnclosureId = -1,
                            Name = "animal_101",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -102,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(271),
                            DateOfBirth = new DateTime(2022, 7, 30, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(269),
                            EnclosureId = -1,
                            Name = "animal_102",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -103,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(290),
                            DateOfBirth = new DateTime(2022, 12, 29, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(288),
                            EnclosureId = -1,
                            Name = "animal_103",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -104,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(310),
                            DateOfBirth = new DateTime(2019, 3, 11, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(308),
                            EnclosureId = -1,
                            Name = "animal_104",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -105,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(333),
                            DateOfBirth = new DateTime(2022, 1, 2, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(331),
                            EnclosureId = -1,
                            Name = "animal_105",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -106,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(358),
                            DateOfBirth = new DateTime(2018, 11, 21, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(356),
                            EnclosureId = -1,
                            Name = "animal_106",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -107,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(378),
                            DateOfBirth = new DateTime(2020, 11, 14, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(376),
                            EnclosureId = -1,
                            Name = "animal_107",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -108,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(398),
                            DateOfBirth = new DateTime(2016, 11, 3, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(396),
                            EnclosureId = -1,
                            Name = "animal_108",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -109,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(465),
                            DateOfBirth = new DateTime(2016, 4, 20, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(463),
                            EnclosureId = -1,
                            Name = "animal_109",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -110,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(505),
                            DateOfBirth = new DateTime(2018, 3, 7, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(503),
                            EnclosureId = -1,
                            Name = "animal_110",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(525),
                            DateOfBirth = new DateTime(2023, 1, 16, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(524),
                            EnclosureId = -1,
                            Name = "animal_111",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -112,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(545),
                            DateOfBirth = new DateTime(2022, 10, 30, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(543),
                            EnclosureId = -1,
                            Name = "animal_112",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -113,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(564),
                            DateOfBirth = new DateTime(2016, 4, 2, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(563),
                            EnclosureId = -1,
                            Name = "animal_113",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -114,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(584),
                            DateOfBirth = new DateTime(2020, 7, 19, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(583),
                            EnclosureId = -1,
                            Name = "animal_114",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -115,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(606),
                            DateOfBirth = new DateTime(2022, 3, 16, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(604),
                            EnclosureId = -1,
                            Name = "animal_115",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -116,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(625),
                            DateOfBirth = new DateTime(2023, 4, 26, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(623),
                            EnclosureId = -1,
                            Name = "animal_116",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -117,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(645),
                            DateOfBirth = new DateTime(2016, 12, 17, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(643),
                            EnclosureId = -1,
                            Name = "animal_117",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -118,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(665),
                            DateOfBirth = new DateTime(2017, 9, 19, 9, 42, 49, 917, DateTimeKind.Utc).AddTicks(664),
                            EnclosureId = -1,
                            Name = "animal_118",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -119,
                            DateOfAquisition = new DateTime(2024, 3, 13, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(685),
                            DateOfBirth = new DateTime(2021, 11, 10, 10, 42, 49, 917, DateTimeKind.Utc).AddTicks(684),
                            EnclosureId = -1,
                            Name = "animal_119",
                            Sex = 0,
                            SpeciesId = -11
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Capacity = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = -2,
                            Capacity = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            Capacity = 10,
                            Type = 2
                        },
                        new
                        {
                            Id = -4,
                            Capacity = 10,
                            Type = 3
                        },
                        new
                        {
                            Id = -5,
                            Capacity = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = -6,
                            Capacity = 10,
                            Type = 5
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 1,
                            Name = "species_2"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 4,
                            Name = "species_3"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 2,
                            Name = "species_4"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 4,
                            Name = "species_5"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 0,
                            Name = "species_6"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 2,
                            Name = "species_7"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 5,
                            Name = "species_8"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 5,
                            Name = "species_9"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 2,
                            Name = "species_10"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 2,
                            Name = "species_11"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
