// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240312210636_EnclosureAnimals")]
    partial class EnclosureAnimals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -20,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7065),
                            DateOfBirth = new DateTime(2016, 8, 30, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7039),
                            EnclosureId = -6,
                            Name = "animal_20",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7143),
                            DateOfBirth = new DateTime(2019, 12, 1, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7141),
                            EnclosureId = -1,
                            Name = "animal_21",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -22,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7167),
                            DateOfBirth = new DateTime(2022, 7, 4, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7166),
                            EnclosureId = -3,
                            Name = "animal_22",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -23,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7192),
                            DateOfBirth = new DateTime(2023, 12, 19, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7190),
                            EnclosureId = -3,
                            Name = "animal_23",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -24,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7212),
                            DateOfBirth = new DateTime(2021, 7, 9, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7210),
                            EnclosureId = -3,
                            Name = "animal_24",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -25,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7231),
                            DateOfBirth = new DateTime(2018, 4, 16, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7230),
                            EnclosureId = -4,
                            Name = "animal_25",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7251),
                            DateOfBirth = new DateTime(2021, 11, 11, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7250),
                            EnclosureId = -1,
                            Name = "animal_26",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -27,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7334),
                            DateOfBirth = new DateTime(2021, 1, 5, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7333),
                            EnclosureId = -2,
                            Name = "animal_27",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -28,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7355),
                            DateOfBirth = new DateTime(2021, 9, 28, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7353),
                            EnclosureId = -1,
                            Name = "animal_28",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -29,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7375),
                            DateOfBirth = new DateTime(2023, 5, 7, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7373),
                            EnclosureId = -5,
                            Name = "animal_29",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -30,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7420),
                            DateOfBirth = new DateTime(2017, 10, 21, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7418),
                            EnclosureId = -4,
                            Name = "animal_30",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7441),
                            DateOfBirth = new DateTime(2016, 8, 11, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7439),
                            EnclosureId = -5,
                            Name = "animal_31",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7461),
                            DateOfBirth = new DateTime(2021, 10, 31, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7459),
                            EnclosureId = -3,
                            Name = "animal_32",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -33,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7629),
                            DateOfBirth = new DateTime(2016, 3, 9, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7627),
                            EnclosureId = -5,
                            Name = "animal_33",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7649),
                            DateOfBirth = new DateTime(2020, 9, 13, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7647),
                            EnclosureId = -4,
                            Name = "animal_34",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -35,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7672),
                            DateOfBirth = new DateTime(2023, 5, 14, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7671),
                            EnclosureId = -2,
                            Name = "animal_35",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -36,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7694),
                            DateOfBirth = new DateTime(2021, 5, 5, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7692),
                            EnclosureId = -4,
                            Name = "animal_36",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -37,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7714),
                            DateOfBirth = new DateTime(2020, 6, 11, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7712),
                            EnclosureId = -1,
                            Name = "animal_37",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -38,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7734),
                            DateOfBirth = new DateTime(2018, 4, 23, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7733),
                            EnclosureId = -2,
                            Name = "animal_38",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7755),
                            DateOfBirth = new DateTime(2019, 3, 30, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7753),
                            EnclosureId = -3,
                            Name = "animal_39",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7793),
                            DateOfBirth = new DateTime(2023, 10, 22, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7791),
                            EnclosureId = -3,
                            Name = "animal_40",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7814),
                            DateOfBirth = new DateTime(2022, 3, 24, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7813),
                            EnclosureId = -2,
                            Name = "animal_41",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -42,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7833),
                            DateOfBirth = new DateTime(2020, 7, 21, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7832),
                            EnclosureId = -5,
                            Name = "animal_42",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7853),
                            DateOfBirth = new DateTime(2018, 7, 2, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7852),
                            EnclosureId = -5,
                            Name = "animal_43",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -44,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7874),
                            DateOfBirth = new DateTime(2016, 4, 25, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7873),
                            EnclosureId = -4,
                            Name = "animal_44",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -45,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7895),
                            DateOfBirth = new DateTime(2019, 10, 14, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7893),
                            EnclosureId = -4,
                            Name = "animal_45",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -46,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7915),
                            DateOfBirth = new DateTime(2019, 9, 20, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7913),
                            EnclosureId = -2,
                            Name = "animal_46",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -47,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(7989),
                            DateOfBirth = new DateTime(2023, 7, 2, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(7988),
                            EnclosureId = -2,
                            Name = "animal_47",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8011),
                            DateOfBirth = new DateTime(2020, 3, 2, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8010),
                            EnclosureId = -3,
                            Name = "animal_48",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -49,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8032),
                            DateOfBirth = new DateTime(2021, 12, 7, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8030),
                            EnclosureId = -4,
                            Name = "animal_49",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -50,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8070),
                            DateOfBirth = new DateTime(2024, 1, 26, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8068),
                            EnclosureId = -1,
                            Name = "animal_50",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8093),
                            DateOfBirth = new DateTime(2020, 8, 16, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8092),
                            EnclosureId = -3,
                            Name = "animal_51",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8115),
                            DateOfBirth = new DateTime(2022, 5, 26, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8114),
                            EnclosureId = -1,
                            Name = "animal_52",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -53,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8136),
                            DateOfBirth = new DateTime(2018, 12, 2, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8134),
                            EnclosureId = -6,
                            Name = "animal_53",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -54,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8156),
                            DateOfBirth = new DateTime(2020, 4, 2, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8155),
                            EnclosureId = -4,
                            Name = "animal_54",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -55,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8176),
                            DateOfBirth = new DateTime(2021, 12, 11, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8175),
                            EnclosureId = -4,
                            Name = "animal_55",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -56,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8197),
                            DateOfBirth = new DateTime(2021, 9, 25, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8195),
                            EnclosureId = -6,
                            Name = "animal_56",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -57,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8218),
                            DateOfBirth = new DateTime(2023, 1, 17, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8216),
                            EnclosureId = -3,
                            Name = "animal_57",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -58,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8237),
                            DateOfBirth = new DateTime(2019, 3, 24, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8236),
                            EnclosureId = -2,
                            Name = "animal_58",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -59,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8257),
                            DateOfBirth = new DateTime(2023, 12, 14, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8256),
                            EnclosureId = -5,
                            Name = "animal_59",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8299),
                            DateOfBirth = new DateTime(2022, 4, 24, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8298),
                            EnclosureId = -5,
                            Name = "animal_60",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8320),
                            DateOfBirth = new DateTime(2017, 1, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8319),
                            EnclosureId = -4,
                            Name = "animal_61",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -62,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8340),
                            DateOfBirth = new DateTime(2019, 9, 15, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8339),
                            EnclosureId = -4,
                            Name = "animal_62",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -63,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8360),
                            DateOfBirth = new DateTime(2018, 4, 26, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8359),
                            EnclosureId = -3,
                            Name = "animal_63",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -64,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8380),
                            DateOfBirth = new DateTime(2018, 11, 25, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8379),
                            EnclosureId = -5,
                            Name = "animal_64",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -65,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8400),
                            DateOfBirth = new DateTime(2018, 6, 29, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8399),
                            EnclosureId = -6,
                            Name = "animal_65",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -66,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8421),
                            DateOfBirth = new DateTime(2022, 10, 8, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8420),
                            EnclosureId = -3,
                            Name = "animal_66",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -67,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8489),
                            DateOfBirth = new DateTime(2018, 3, 23, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8487),
                            EnclosureId = -3,
                            Name = "animal_67",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -68,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8511),
                            DateOfBirth = new DateTime(2018, 6, 28, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8510),
                            EnclosureId = -3,
                            Name = "animal_68",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -69,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8532),
                            DateOfBirth = new DateTime(2016, 1, 13, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8530),
                            EnclosureId = -3,
                            Name = "animal_69",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -70,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8570),
                            DateOfBirth = new DateTime(2019, 4, 24, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8568),
                            EnclosureId = -3,
                            Name = "animal_70",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8597),
                            DateOfBirth = new DateTime(2021, 12, 13, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8594),
                            EnclosureId = -2,
                            Name = "animal_71",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -72,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8658),
                            DateOfBirth = new DateTime(2018, 5, 21, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8648),
                            EnclosureId = -3,
                            Name = "animal_72",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8735),
                            DateOfBirth = new DateTime(2022, 11, 14, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8732),
                            EnclosureId = -5,
                            Name = "animal_73",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -74,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8783),
                            DateOfBirth = new DateTime(2020, 5, 2, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8781),
                            EnclosureId = -3,
                            Name = "animal_74",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -75,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8888),
                            DateOfBirth = new DateTime(2017, 5, 26, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8878),
                            EnclosureId = -4,
                            Name = "animal_75",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -76,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8926),
                            DateOfBirth = new DateTime(2016, 8, 30, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8924),
                            EnclosureId = -1,
                            Name = "animal_76",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -77,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8948),
                            DateOfBirth = new DateTime(2022, 10, 9, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8947),
                            EnclosureId = -5,
                            Name = "animal_77",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -78,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8968),
                            DateOfBirth = new DateTime(2017, 3, 15, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8967),
                            EnclosureId = -2,
                            Name = "animal_78",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(8989),
                            DateOfBirth = new DateTime(2016, 10, 8, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(8988),
                            EnclosureId = -3,
                            Name = "animal_79",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -80,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9037),
                            DateOfBirth = new DateTime(2019, 6, 11, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9035),
                            EnclosureId = -2,
                            Name = "animal_80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9059),
                            DateOfBirth = new DateTime(2023, 7, 9, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9057),
                            EnclosureId = -3,
                            Name = "animal_81",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -82,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9080),
                            DateOfBirth = new DateTime(2020, 10, 6, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9078),
                            EnclosureId = -4,
                            Name = "animal_82",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -83,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9105),
                            DateOfBirth = new DateTime(2022, 10, 15, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9103),
                            EnclosureId = -4,
                            Name = "animal_83",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -84,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9125),
                            DateOfBirth = new DateTime(2017, 6, 16, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9124),
                            EnclosureId = -6,
                            Name = "animal_84",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -85,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9146),
                            DateOfBirth = new DateTime(2023, 10, 18, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9144),
                            EnclosureId = -4,
                            Name = "animal_85",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -86,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9324),
                            DateOfBirth = new DateTime(2022, 3, 13, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9322),
                            EnclosureId = -4,
                            Name = "animal_86",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -87,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9345),
                            DateOfBirth = new DateTime(2019, 9, 12, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9343),
                            EnclosureId = -5,
                            Name = "animal_87",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -88,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9365),
                            DateOfBirth = new DateTime(2018, 6, 11, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9363),
                            EnclosureId = -2,
                            Name = "animal_88",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -89,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9385),
                            DateOfBirth = new DateTime(2023, 1, 17, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9384),
                            EnclosureId = -4,
                            Name = "animal_89",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -90,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9430),
                            DateOfBirth = new DateTime(2019, 9, 20, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9428),
                            EnclosureId = -2,
                            Name = "animal_90",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9451),
                            DateOfBirth = new DateTime(2019, 7, 20, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9450),
                            EnclosureId = -5,
                            Name = "animal_91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -92,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9471),
                            DateOfBirth = new DateTime(2020, 12, 26, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9470),
                            EnclosureId = -5,
                            Name = "animal_92",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -93,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9491),
                            DateOfBirth = new DateTime(2019, 6, 8, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9489),
                            EnclosureId = -3,
                            Name = "animal_93",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -94,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9511),
                            DateOfBirth = new DateTime(2024, 2, 1, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9510),
                            EnclosureId = -2,
                            Name = "animal_94",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -95,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9531),
                            DateOfBirth = new DateTime(2016, 3, 5, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9530),
                            EnclosureId = -4,
                            Name = "animal_95",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -96,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9551),
                            DateOfBirth = new DateTime(2023, 10, 10, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9550),
                            EnclosureId = -1,
                            Name = "animal_96",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -97,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9571),
                            DateOfBirth = new DateTime(2022, 5, 14, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9569),
                            EnclosureId = -2,
                            Name = "animal_97",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -98,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9591),
                            DateOfBirth = new DateTime(2017, 2, 14, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9590),
                            EnclosureId = -6,
                            Name = "animal_98",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -99,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9611),
                            DateOfBirth = new DateTime(2017, 6, 15, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9610),
                            EnclosureId = -6,
                            Name = "animal_99",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -100,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9654),
                            DateOfBirth = new DateTime(2020, 8, 13, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9652),
                            EnclosureId = -1,
                            Name = "animal_100",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9674),
                            DateOfBirth = new DateTime(2015, 12, 27, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9673),
                            EnclosureId = -4,
                            Name = "animal_101",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -102,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9694),
                            DateOfBirth = new DateTime(2016, 9, 28, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9692),
                            EnclosureId = -6,
                            Name = "animal_102",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -103,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9714),
                            DateOfBirth = new DateTime(2022, 2, 26, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9713),
                            EnclosureId = -5,
                            Name = "animal_103",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -104,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9735),
                            DateOfBirth = new DateTime(2019, 10, 4, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9734),
                            EnclosureId = -2,
                            Name = "animal_104",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -105,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9755),
                            DateOfBirth = new DateTime(2022, 8, 24, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9754),
                            EnclosureId = -3,
                            Name = "animal_105",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -106,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9776),
                            DateOfBirth = new DateTime(2019, 10, 23, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9775),
                            EnclosureId = -1,
                            Name = "animal_106",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -107,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9865),
                            DateOfBirth = new DateTime(2022, 2, 2, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9863),
                            EnclosureId = -6,
                            Name = "animal_107",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -108,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9885),
                            DateOfBirth = new DateTime(2022, 10, 10, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9884),
                            EnclosureId = -2,
                            Name = "animal_108",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -109,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9905),
                            DateOfBirth = new DateTime(2022, 12, 26, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9904),
                            EnclosureId = -6,
                            Name = "animal_109",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -110,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9943),
                            DateOfBirth = new DateTime(2016, 1, 23, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9941),
                            EnclosureId = -2,
                            Name = "animal_110",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9964),
                            DateOfBirth = new DateTime(2022, 11, 22, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9962),
                            EnclosureId = -4,
                            Name = "animal_111",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -112,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 844, DateTimeKind.Utc).AddTicks(9984),
                            DateOfBirth = new DateTime(2020, 9, 22, 20, 6, 35, 844, DateTimeKind.Utc).AddTicks(9982),
                            EnclosureId = -4,
                            Name = "animal_112",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -113,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(4),
                            DateOfBirth = new DateTime(2020, 10, 19, 20, 6, 35, 845, DateTimeKind.Utc).AddTicks(3),
                            EnclosureId = -3,
                            Name = "animal_113",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -114,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(24),
                            DateOfBirth = new DateTime(2022, 3, 4, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(23),
                            EnclosureId = -1,
                            Name = "animal_114",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -115,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(45),
                            DateOfBirth = new DateTime(2020, 5, 10, 20, 6, 35, 845, DateTimeKind.Utc).AddTicks(43),
                            EnclosureId = -5,
                            Name = "animal_115",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -116,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(65),
                            DateOfBirth = new DateTime(2020, 9, 18, 20, 6, 35, 845, DateTimeKind.Utc).AddTicks(64),
                            EnclosureId = -2,
                            Name = "animal_116",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -117,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(85),
                            DateOfBirth = new DateTime(2021, 10, 9, 20, 6, 35, 845, DateTimeKind.Utc).AddTicks(83),
                            EnclosureId = -2,
                            Name = "animal_117",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -118,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(105),
                            DateOfBirth = new DateTime(2020, 10, 12, 20, 6, 35, 845, DateTimeKind.Utc).AddTicks(104),
                            EnclosureId = -4,
                            Name = "animal_118",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -119,
                            DateOfAquisition = new DateTime(2024, 3, 12, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(126),
                            DateOfBirth = new DateTime(2021, 11, 12, 21, 6, 35, 845, DateTimeKind.Utc).AddTicks(124),
                            EnclosureId = -2,
                            Name = "animal_119",
                            Sex = 0,
                            SpeciesId = -11
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Capacity = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = -2,
                            Capacity = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            Capacity = 10,
                            Type = 2
                        },
                        new
                        {
                            Id = -4,
                            Capacity = 10,
                            Type = 3
                        },
                        new
                        {
                            Id = -5,
                            Capacity = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = -6,
                            Capacity = 10,
                            Type = 5
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 4,
                            Name = "species_2"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 2,
                            Name = "species_3"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 0,
                            Name = "species_4"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 2,
                            Name = "species_5"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 2,
                            Name = "species_6"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 4,
                            Name = "species_7"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 2,
                            Name = "species_8"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 1,
                            Name = "species_9"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 0,
                            Name = "species_10"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 2,
                            Name = "species_11"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
