// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240313141717_EnclosureOutOfConstructor")]
    partial class EnclosureOutOfConstructor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -20,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(7640),
                            DateOfBirth = new DateTime(2016, 10, 21, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(7624),
                            EnclosureId = -3,
                            Name = "animal_20",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(7694),
                            DateOfBirth = new DateTime(2022, 11, 20, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(7692),
                            EnclosureId = -2,
                            Name = "animal_21",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -22,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(7712),
                            DateOfBirth = new DateTime(2021, 11, 8, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(7711),
                            EnclosureId = -6,
                            Name = "animal_22",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -23,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(7738),
                            DateOfBirth = new DateTime(2023, 5, 25, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(7736),
                            EnclosureId = -5,
                            Name = "animal_23",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -24,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(7971),
                            DateOfBirth = new DateTime(2020, 6, 24, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(7955),
                            EnclosureId = -1,
                            Name = "animal_24",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -25,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8288),
                            DateOfBirth = new DateTime(2018, 9, 19, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8278),
                            EnclosureId = -4,
                            Name = "animal_25",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8404),
                            DateOfBirth = new DateTime(2019, 5, 31, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8398),
                            EnclosureId = -2,
                            Name = "animal_26",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -27,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8436),
                            DateOfBirth = new DateTime(2019, 5, 30, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8434),
                            EnclosureId = -4,
                            Name = "animal_27",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -28,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8457),
                            DateOfBirth = new DateTime(2022, 2, 8, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8455),
                            EnclosureId = -5,
                            Name = "animal_28",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -29,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8478),
                            DateOfBirth = new DateTime(2020, 10, 16, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8476),
                            EnclosureId = -5,
                            Name = "animal_29",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -30,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8528),
                            DateOfBirth = new DateTime(2021, 6, 9, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8527),
                            EnclosureId = -5,
                            Name = "animal_30",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8550),
                            DateOfBirth = new DateTime(2022, 4, 8, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8548),
                            EnclosureId = -3,
                            Name = "animal_31",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8571),
                            DateOfBirth = new DateTime(2023, 8, 14, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8569),
                            EnclosureId = -2,
                            Name = "animal_32",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -33,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8768),
                            DateOfBirth = new DateTime(2023, 8, 18, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8766),
                            EnclosureId = -5,
                            Name = "animal_33",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8789),
                            DateOfBirth = new DateTime(2019, 4, 13, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(8787),
                            EnclosureId = -1,
                            Name = "animal_34",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -35,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8811),
                            DateOfBirth = new DateTime(2021, 3, 8, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(8810),
                            EnclosureId = -1,
                            Name = "animal_35",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -36,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9104),
                            DateOfBirth = new DateTime(2023, 3, 29, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9102),
                            EnclosureId = -6,
                            Name = "animal_36",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -37,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9129),
                            DateOfBirth = new DateTime(2018, 8, 15, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9128),
                            EnclosureId = -2,
                            Name = "animal_37",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -38,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9150),
                            DateOfBirth = new DateTime(2022, 9, 4, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9148),
                            EnclosureId = -1,
                            Name = "animal_38",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9317),
                            DateOfBirth = new DateTime(2019, 3, 19, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9316),
                            EnclosureId = -1,
                            Name = "animal_39",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9354),
                            DateOfBirth = new DateTime(2016, 10, 17, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9353),
                            EnclosureId = -6,
                            Name = "animal_40",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9375),
                            DateOfBirth = new DateTime(2023, 6, 16, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9373),
                            EnclosureId = -6,
                            Name = "animal_41",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -42,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9394),
                            DateOfBirth = new DateTime(2021, 3, 6, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9393),
                            EnclosureId = -1,
                            Name = "animal_42",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9413),
                            DateOfBirth = new DateTime(2018, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9412),
                            EnclosureId = -6,
                            Name = "animal_43",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -44,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9433),
                            DateOfBirth = new DateTime(2019, 11, 11, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9432),
                            EnclosureId = -1,
                            Name = "animal_44",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -45,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9453),
                            DateOfBirth = new DateTime(2022, 10, 5, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9451),
                            EnclosureId = -3,
                            Name = "animal_45",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -46,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9472),
                            DateOfBirth = new DateTime(2019, 10, 13, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9471),
                            EnclosureId = -1,
                            Name = "animal_46",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -47,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9492),
                            DateOfBirth = new DateTime(2022, 7, 16, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9491),
                            EnclosureId = -3,
                            Name = "animal_47",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9511),
                            DateOfBirth = new DateTime(2017, 3, 31, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9510),
                            EnclosureId = -5,
                            Name = "animal_48",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -49,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9531),
                            DateOfBirth = new DateTime(2023, 5, 16, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9529),
                            EnclosureId = -4,
                            Name = "animal_49",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -50,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9568),
                            DateOfBirth = new DateTime(2019, 8, 27, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9567),
                            EnclosureId = -6,
                            Name = "animal_50",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9731),
                            DateOfBirth = new DateTime(2020, 12, 26, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9730),
                            EnclosureId = -6,
                            Name = "animal_51",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9751),
                            DateOfBirth = new DateTime(2017, 4, 22, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9750),
                            EnclosureId = -1,
                            Name = "animal_52",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -53,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9770),
                            DateOfBirth = new DateTime(2017, 9, 2, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9769),
                            EnclosureId = -1,
                            Name = "animal_53",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -54,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9789),
                            DateOfBirth = new DateTime(2018, 5, 10, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9787),
                            EnclosureId = -5,
                            Name = "animal_54",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -55,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9807),
                            DateOfBirth = new DateTime(2022, 9, 21, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9806),
                            EnclosureId = -4,
                            Name = "animal_55",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -56,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9875),
                            DateOfBirth = new DateTime(2023, 1, 5, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9873),
                            EnclosureId = -5,
                            Name = "animal_56",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -57,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9896),
                            DateOfBirth = new DateTime(2017, 5, 21, 13, 17, 17, 349, DateTimeKind.Utc).AddTicks(9894),
                            EnclosureId = -4,
                            Name = "animal_57",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -58,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9913),
                            DateOfBirth = new DateTime(2019, 2, 24, 14, 17, 17, 349, DateTimeKind.Utc).AddTicks(9912),
                            EnclosureId = -5,
                            Name = "animal_58",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -59,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(136),
                            DateOfBirth = new DateTime(2020, 7, 23, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(133),
                            EnclosureId = -2,
                            Name = "animal_59",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(182),
                            DateOfBirth = new DateTime(2018, 6, 17, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(180),
                            EnclosureId = -5,
                            Name = "animal_60",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(201),
                            DateOfBirth = new DateTime(2018, 7, 13, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(200),
                            EnclosureId = -1,
                            Name = "animal_61",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -62,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(221),
                            DateOfBirth = new DateTime(2021, 11, 11, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(219),
                            EnclosureId = -3,
                            Name = "animal_62",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -63,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(241),
                            DateOfBirth = new DateTime(2020, 8, 25, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(239),
                            EnclosureId = -5,
                            Name = "animal_63",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -64,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(261),
                            DateOfBirth = new DateTime(2021, 7, 23, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(260),
                            EnclosureId = -4,
                            Name = "animal_64",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -65,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(280),
                            DateOfBirth = new DateTime(2023, 5, 18, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(279),
                            EnclosureId = -5,
                            Name = "animal_65",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -66,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(518),
                            DateOfBirth = new DateTime(2021, 12, 2, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(517),
                            EnclosureId = -6,
                            Name = "animal_66",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -67,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(538),
                            DateOfBirth = new DateTime(2021, 2, 7, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(536),
                            EnclosureId = -4,
                            Name = "animal_67",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -68,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(557),
                            DateOfBirth = new DateTime(2019, 1, 9, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(556),
                            EnclosureId = -2,
                            Name = "animal_68",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -69,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(576),
                            DateOfBirth = new DateTime(2016, 8, 26, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(575),
                            EnclosureId = -6,
                            Name = "animal_69",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -70,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(614),
                            DateOfBirth = new DateTime(2016, 5, 28, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(613),
                            EnclosureId = -3,
                            Name = "animal_70",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(635),
                            DateOfBirth = new DateTime(2018, 4, 15, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(634),
                            EnclosureId = -3,
                            Name = "animal_71",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -72,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(655),
                            DateOfBirth = new DateTime(2023, 8, 23, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(654),
                            EnclosureId = -4,
                            Name = "animal_72",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(675),
                            DateOfBirth = new DateTime(2022, 1, 20, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(674),
                            EnclosureId = -6,
                            Name = "animal_73",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -74,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(695),
                            DateOfBirth = new DateTime(2022, 2, 8, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(693),
                            EnclosureId = -5,
                            Name = "animal_74",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -75,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(714),
                            DateOfBirth = new DateTime(2019, 7, 16, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(712),
                            EnclosureId = -1,
                            Name = "animal_75",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -76,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(734),
                            DateOfBirth = new DateTime(2017, 3, 22, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(732),
                            EnclosureId = -5,
                            Name = "animal_76",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -77,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(753),
                            DateOfBirth = new DateTime(2021, 3, 26, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(751),
                            EnclosureId = -4,
                            Name = "animal_77",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -78,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(860),
                            DateOfBirth = new DateTime(2017, 1, 29, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(858),
                            EnclosureId = -3,
                            Name = "animal_78",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(880),
                            DateOfBirth = new DateTime(2020, 4, 2, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(879),
                            EnclosureId = -5,
                            Name = "animal_79",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -80,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(920),
                            DateOfBirth = new DateTime(2018, 8, 12, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(918),
                            EnclosureId = -5,
                            Name = "animal_80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(939),
                            DateOfBirth = new DateTime(2020, 6, 19, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(938),
                            EnclosureId = -3,
                            Name = "animal_81",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -82,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(960),
                            DateOfBirth = new DateTime(2021, 5, 4, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(959),
                            EnclosureId = -6,
                            Name = "animal_82",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -83,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1125),
                            DateOfBirth = new DateTime(2019, 10, 9, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1123),
                            EnclosureId = -2,
                            Name = "animal_83",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -84,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1146),
                            DateOfBirth = new DateTime(2018, 5, 2, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1144),
                            EnclosureId = -2,
                            Name = "animal_84",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -85,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1165),
                            DateOfBirth = new DateTime(2022, 6, 2, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1163),
                            EnclosureId = -5,
                            Name = "animal_85",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -86,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1183),
                            DateOfBirth = new DateTime(2023, 12, 8, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1182),
                            EnclosureId = -6,
                            Name = "animal_86",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -87,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1396),
                            DateOfBirth = new DateTime(2017, 8, 23, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1392),
                            EnclosureId = -4,
                            Name = "animal_87",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -88,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1414),
                            DateOfBirth = new DateTime(2021, 2, 2, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1413),
                            EnclosureId = -1,
                            Name = "animal_88",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -89,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1432),
                            DateOfBirth = new DateTime(2019, 6, 26, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1431),
                            EnclosureId = -5,
                            Name = "animal_89",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -90,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1466),
                            DateOfBirth = new DateTime(2023, 11, 9, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1465),
                            EnclosureId = -2,
                            Name = "animal_90",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1484),
                            DateOfBirth = new DateTime(2018, 10, 21, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1483),
                            EnclosureId = -3,
                            Name = "animal_91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -92,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1501),
                            DateOfBirth = new DateTime(2019, 4, 23, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1500),
                            EnclosureId = -4,
                            Name = "animal_92",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -93,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1519),
                            DateOfBirth = new DateTime(2018, 10, 29, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1518),
                            EnclosureId = -3,
                            Name = "animal_93",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -94,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1539),
                            DateOfBirth = new DateTime(2022, 10, 17, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1537),
                            EnclosureId = -1,
                            Name = "animal_94",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -95,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1641),
                            DateOfBirth = new DateTime(2017, 7, 23, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1638),
                            EnclosureId = -1,
                            Name = "animal_95",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -96,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1660),
                            DateOfBirth = new DateTime(2022, 9, 12, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1659),
                            EnclosureId = -5,
                            Name = "animal_96",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -97,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1679),
                            DateOfBirth = new DateTime(2020, 1, 24, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1678),
                            EnclosureId = -4,
                            Name = "animal_97",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -98,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1696),
                            DateOfBirth = new DateTime(2020, 5, 18, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1695),
                            EnclosureId = -2,
                            Name = "animal_98",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -99,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1715),
                            DateOfBirth = new DateTime(2020, 7, 10, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1713),
                            EnclosureId = -2,
                            Name = "animal_99",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -100,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1756),
                            DateOfBirth = new DateTime(2019, 6, 29, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1754),
                            EnclosureId = -3,
                            Name = "animal_100",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1774),
                            DateOfBirth = new DateTime(2021, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1772),
                            EnclosureId = -5,
                            Name = "animal_101",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -102,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1791),
                            DateOfBirth = new DateTime(2018, 12, 23, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1790),
                            EnclosureId = -4,
                            Name = "animal_102",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -103,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1809),
                            DateOfBirth = new DateTime(2017, 12, 18, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1807),
                            EnclosureId = -3,
                            Name = "animal_103",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -104,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1826),
                            DateOfBirth = new DateTime(2023, 12, 4, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1825),
                            EnclosureId = -4,
                            Name = "animal_104",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -105,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1843),
                            DateOfBirth = new DateTime(2019, 2, 6, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1842),
                            EnclosureId = -1,
                            Name = "animal_105",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -106,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1860),
                            DateOfBirth = new DateTime(2019, 9, 29, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1859),
                            EnclosureId = -1,
                            Name = "animal_106",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -107,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1878),
                            DateOfBirth = new DateTime(2016, 4, 9, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1877),
                            EnclosureId = -3,
                            Name = "animal_107",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -108,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1895),
                            DateOfBirth = new DateTime(2020, 5, 9, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1894),
                            EnclosureId = -2,
                            Name = "animal_108",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -109,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1913),
                            DateOfBirth = new DateTime(2021, 7, 17, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1912),
                            EnclosureId = -6,
                            Name = "animal_109",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -110,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1946),
                            DateOfBirth = new DateTime(2017, 8, 2, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1944),
                            EnclosureId = -1,
                            Name = "animal_110",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1964),
                            DateOfBirth = new DateTime(2023, 9, 18, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1962),
                            EnclosureId = -1,
                            Name = "animal_111",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -112,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1981),
                            DateOfBirth = new DateTime(2023, 11, 12, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1980),
                            EnclosureId = -4,
                            Name = "animal_112",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -113,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(1999),
                            DateOfBirth = new DateTime(2017, 10, 28, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(1997),
                            EnclosureId = -5,
                            Name = "animal_113",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -114,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(2016),
                            DateOfBirth = new DateTime(2017, 8, 6, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(2015),
                            EnclosureId = -4,
                            Name = "animal_114",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -115,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(2034),
                            DateOfBirth = new DateTime(2021, 5, 22, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(2033),
                            EnclosureId = -1,
                            Name = "animal_115",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -116,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(2113),
                            DateOfBirth = new DateTime(2019, 12, 3, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(2111),
                            EnclosureId = -1,
                            Name = "animal_116",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -117,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(2132),
                            DateOfBirth = new DateTime(2021, 4, 22, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(2131),
                            EnclosureId = -1,
                            Name = "animal_117",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -118,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(2150),
                            DateOfBirth = new DateTime(2017, 2, 22, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(2149),
                            EnclosureId = -3,
                            Name = "animal_118",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -119,
                            DateOfAquisition = new DateTime(2024, 3, 13, 14, 17, 17, 350, DateTimeKind.Utc).AddTicks(2167),
                            DateOfBirth = new DateTime(2022, 9, 23, 13, 17, 17, 350, DateTimeKind.Utc).AddTicks(2166),
                            EnclosureId = -6,
                            Name = "animal_119",
                            Sex = 1,
                            SpeciesId = -11
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Capacity = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = -2,
                            Capacity = 50,
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            Capacity = 40,
                            Type = 2
                        },
                        new
                        {
                            Id = -4,
                            Capacity = 6,
                            Type = 3
                        },
                        new
                        {
                            Id = -5,
                            Capacity = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = -6,
                            Capacity = 1000,
                            Type = 5
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 3,
                            Name = "species_2"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 3,
                            Name = "species_3"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 1,
                            Name = "species_4"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 3,
                            Name = "species_5"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 4,
                            Name = "species_6"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 3,
                            Name = "species_7"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 0,
                            Name = "species_8"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 5,
                            Name = "species_9"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 1,
                            Name = "species_10"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 1,
                            Name = "species_11"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
