// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240313122637_EnclosureAlmost")]
    partial class EnclosureAlmost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EnclosureId = -1,
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -20,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7164),
                            DateOfBirth = new DateTime(2023, 9, 20, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7148),
                            EnclosureId = -6,
                            Name = "animal_20",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7191),
                            DateOfBirth = new DateTime(2021, 5, 29, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7190),
                            EnclosureId = -6,
                            Name = "animal_21",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -22,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7256),
                            DateOfBirth = new DateTime(2021, 7, 27, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7255),
                            EnclosureId = -5,
                            Name = "animal_22",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -23,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7279),
                            DateOfBirth = new DateTime(2019, 4, 24, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7278),
                            EnclosureId = -2,
                            Name = "animal_23",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -24,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7299),
                            DateOfBirth = new DateTime(2022, 11, 8, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7297),
                            EnclosureId = -3,
                            Name = "animal_24",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -25,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7316),
                            DateOfBirth = new DateTime(2021, 12, 18, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7315),
                            EnclosureId = -1,
                            Name = "animal_25",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7334),
                            DateOfBirth = new DateTime(2021, 12, 3, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7332),
                            EnclosureId = -1,
                            Name = "animal_26",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -27,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7352),
                            DateOfBirth = new DateTime(2021, 3, 2, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7351),
                            EnclosureId = -5,
                            Name = "animal_27",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -28,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7370),
                            DateOfBirth = new DateTime(2021, 12, 31, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7369),
                            EnclosureId = -6,
                            Name = "animal_28",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -29,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7387),
                            DateOfBirth = new DateTime(2021, 2, 5, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7386),
                            EnclosureId = -5,
                            Name = "animal_29",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -30,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7423),
                            DateOfBirth = new DateTime(2021, 4, 9, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7421),
                            EnclosureId = -2,
                            Name = "animal_30",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7440),
                            DateOfBirth = new DateTime(2020, 2, 5, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7439),
                            EnclosureId = -5,
                            Name = "animal_31",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7458),
                            DateOfBirth = new DateTime(2018, 3, 22, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7457),
                            EnclosureId = -3,
                            Name = "animal_32",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -33,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7475),
                            DateOfBirth = new DateTime(2020, 7, 30, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7474),
                            EnclosureId = -3,
                            Name = "animal_33",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7493),
                            DateOfBirth = new DateTime(2018, 6, 12, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7491),
                            EnclosureId = -2,
                            Name = "animal_34",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -35,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7512),
                            DateOfBirth = new DateTime(2018, 9, 2, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7511),
                            EnclosureId = -5,
                            Name = "animal_35",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -36,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7530),
                            DateOfBirth = new DateTime(2017, 1, 17, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7529),
                            EnclosureId = -2,
                            Name = "animal_36",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -37,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7548),
                            DateOfBirth = new DateTime(2019, 6, 11, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7546),
                            EnclosureId = -2,
                            Name = "animal_37",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -38,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7565),
                            DateOfBirth = new DateTime(2022, 12, 10, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7564),
                            EnclosureId = -6,
                            Name = "animal_38",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7582),
                            DateOfBirth = new DateTime(2023, 9, 11, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7581),
                            EnclosureId = -3,
                            Name = "animal_39",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7615),
                            DateOfBirth = new DateTime(2023, 11, 17, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7614),
                            EnclosureId = -6,
                            Name = "animal_40",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7638),
                            DateOfBirth = new DateTime(2021, 9, 12, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7632),
                            EnclosureId = -3,
                            Name = "animal_41",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -42,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7700),
                            DateOfBirth = new DateTime(2016, 1, 11, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7699),
                            EnclosureId = -5,
                            Name = "animal_42",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7721),
                            DateOfBirth = new DateTime(2019, 1, 8, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7720),
                            EnclosureId = -3,
                            Name = "animal_43",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -44,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7739),
                            DateOfBirth = new DateTime(2019, 12, 31, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7737),
                            EnclosureId = -5,
                            Name = "animal_44",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -45,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7757),
                            DateOfBirth = new DateTime(2021, 10, 9, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7755),
                            EnclosureId = -6,
                            Name = "animal_45",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -46,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7774),
                            DateOfBirth = new DateTime(2019, 1, 11, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7773),
                            EnclosureId = -1,
                            Name = "animal_46",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -47,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7791),
                            DateOfBirth = new DateTime(2017, 10, 25, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7790),
                            EnclosureId = -6,
                            Name = "animal_47",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7809),
                            DateOfBirth = new DateTime(2022, 2, 20, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7807),
                            EnclosureId = -1,
                            Name = "animal_48",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -49,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7826),
                            DateOfBirth = new DateTime(2021, 7, 21, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7824),
                            EnclosureId = -5,
                            Name = "animal_49",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -50,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7861),
                            DateOfBirth = new DateTime(2018, 2, 3, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7859),
                            EnclosureId = -3,
                            Name = "animal_50",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7880),
                            DateOfBirth = new DateTime(2020, 4, 18, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7879),
                            EnclosureId = -4,
                            Name = "animal_51",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7898),
                            DateOfBirth = new DateTime(2018, 12, 30, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7897),
                            EnclosureId = -5,
                            Name = "animal_52",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -53,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7915),
                            DateOfBirth = new DateTime(2017, 11, 6, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7914),
                            EnclosureId = -5,
                            Name = "animal_53",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -54,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7933),
                            DateOfBirth = new DateTime(2019, 9, 29, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7931),
                            EnclosureId = -1,
                            Name = "animal_54",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -55,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7950),
                            DateOfBirth = new DateTime(2017, 12, 26, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7949),
                            EnclosureId = -1,
                            Name = "animal_55",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -56,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7967),
                            DateOfBirth = new DateTime(2023, 12, 8, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7966),
                            EnclosureId = -2,
                            Name = "animal_56",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -57,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(7984),
                            DateOfBirth = new DateTime(2020, 6, 11, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(7983),
                            EnclosureId = -4,
                            Name = "animal_57",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -58,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8002),
                            DateOfBirth = new DateTime(2017, 6, 30, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8000),
                            EnclosureId = -3,
                            Name = "animal_58",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -59,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8019),
                            DateOfBirth = new DateTime(2019, 1, 15, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8018),
                            EnclosureId = -5,
                            Name = "animal_59",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8057),
                            DateOfBirth = new DateTime(2023, 9, 25, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8056),
                            EnclosureId = -1,
                            Name = "animal_60",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8075),
                            DateOfBirth = new DateTime(2021, 8, 25, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8073),
                            EnclosureId = -5,
                            Name = "animal_61",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -62,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8132),
                            DateOfBirth = new DateTime(2024, 2, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8130),
                            EnclosureId = -4,
                            Name = "animal_62",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -63,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8152),
                            DateOfBirth = new DateTime(2023, 9, 21, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8151),
                            EnclosureId = -6,
                            Name = "animal_63",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -64,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8170),
                            DateOfBirth = new DateTime(2017, 8, 30, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8169),
                            EnclosureId = -4,
                            Name = "animal_64",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -65,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8188),
                            DateOfBirth = new DateTime(2016, 2, 8, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8186),
                            EnclosureId = -3,
                            Name = "animal_65",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -66,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8205),
                            DateOfBirth = new DateTime(2019, 4, 16, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8204),
                            EnclosureId = -5,
                            Name = "animal_66",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -67,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8223),
                            DateOfBirth = new DateTime(2017, 5, 22, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8222),
                            EnclosureId = -5,
                            Name = "animal_67",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -68,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8241),
                            DateOfBirth = new DateTime(2018, 3, 28, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8240),
                            EnclosureId = -4,
                            Name = "animal_68",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -69,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8258),
                            DateOfBirth = new DateTime(2019, 2, 27, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8257),
                            EnclosureId = -4,
                            Name = "animal_69",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -70,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8292),
                            DateOfBirth = new DateTime(2016, 10, 26, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8290),
                            EnclosureId = -6,
                            Name = "animal_70",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8310),
                            DateOfBirth = new DateTime(2021, 7, 29, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8309),
                            EnclosureId = -6,
                            Name = "animal_71",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -72,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8327),
                            DateOfBirth = new DateTime(2018, 10, 11, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8326),
                            EnclosureId = -4,
                            Name = "animal_72",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8344),
                            DateOfBirth = new DateTime(2021, 8, 13, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8343),
                            EnclosureId = -5,
                            Name = "animal_73",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -74,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8361),
                            DateOfBirth = new DateTime(2020, 9, 10, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8360),
                            EnclosureId = -6,
                            Name = "animal_74",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -75,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8379),
                            DateOfBirth = new DateTime(2017, 8, 11, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8377),
                            EnclosureId = -2,
                            Name = "animal_75",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -76,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8396),
                            DateOfBirth = new DateTime(2022, 9, 21, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8395),
                            EnclosureId = -5,
                            Name = "animal_76",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -77,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8413),
                            DateOfBirth = new DateTime(2020, 5, 29, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8412),
                            EnclosureId = -4,
                            Name = "animal_77",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -78,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8430),
                            DateOfBirth = new DateTime(2018, 7, 26, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8429),
                            EnclosureId = -2,
                            Name = "animal_78",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8447),
                            DateOfBirth = new DateTime(2018, 3, 23, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8446),
                            EnclosureId = -5,
                            Name = "animal_79",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -80,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8480),
                            DateOfBirth = new DateTime(2018, 10, 8, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8478),
                            EnclosureId = -1,
                            Name = "animal_80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8497),
                            DateOfBirth = new DateTime(2016, 12, 30, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8496),
                            EnclosureId = -5,
                            Name = "animal_81",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -82,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8515),
                            DateOfBirth = new DateTime(2020, 7, 23, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8513),
                            EnclosureId = -2,
                            Name = "animal_82",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -83,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8558),
                            DateOfBirth = new DateTime(2016, 6, 25, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8557),
                            EnclosureId = -1,
                            Name = "animal_83",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -84,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8578),
                            DateOfBirth = new DateTime(2023, 3, 20, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8577),
                            EnclosureId = -4,
                            Name = "animal_84",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -85,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8596),
                            DateOfBirth = new DateTime(2022, 3, 14, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8595),
                            EnclosureId = -5,
                            Name = "animal_85",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -86,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8612),
                            DateOfBirth = new DateTime(2020, 8, 29, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8611),
                            EnclosureId = -5,
                            Name = "animal_86",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -87,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8630),
                            DateOfBirth = new DateTime(2016, 8, 18, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8629),
                            EnclosureId = -2,
                            Name = "animal_87",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -88,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8647),
                            DateOfBirth = new DateTime(2018, 9, 2, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8646),
                            EnclosureId = -1,
                            Name = "animal_88",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -89,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8665),
                            DateOfBirth = new DateTime(2021, 8, 4, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8664),
                            EnclosureId = -6,
                            Name = "animal_89",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -90,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8699),
                            DateOfBirth = new DateTime(2022, 11, 29, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8698),
                            EnclosureId = -6,
                            Name = "animal_90",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8718),
                            DateOfBirth = new DateTime(2021, 3, 5, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8716),
                            EnclosureId = -4,
                            Name = "animal_91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -92,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8735),
                            DateOfBirth = new DateTime(2017, 7, 29, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8734),
                            EnclosureId = -3,
                            Name = "animal_92",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -93,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8752),
                            DateOfBirth = new DateTime(2023, 10, 21, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8751),
                            EnclosureId = -1,
                            Name = "animal_93",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -94,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8769),
                            DateOfBirth = new DateTime(2023, 3, 16, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8768),
                            EnclosureId = -2,
                            Name = "animal_94",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -95,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8786),
                            DateOfBirth = new DateTime(2020, 8, 23, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8785),
                            EnclosureId = -1,
                            Name = "animal_95",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -96,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8804),
                            DateOfBirth = new DateTime(2020, 8, 5, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8803),
                            EnclosureId = -1,
                            Name = "animal_96",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -97,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8821),
                            DateOfBirth = new DateTime(2022, 12, 1, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8820),
                            EnclosureId = -5,
                            Name = "animal_97",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -98,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8838),
                            DateOfBirth = new DateTime(2023, 7, 25, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8837),
                            EnclosureId = -3,
                            Name = "animal_98",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -99,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8855),
                            DateOfBirth = new DateTime(2021, 10, 26, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8853),
                            EnclosureId = -5,
                            Name = "animal_99",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -100,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8892),
                            DateOfBirth = new DateTime(2023, 12, 23, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8891),
                            EnclosureId = -1,
                            Name = "animal_100",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(8987),
                            DateOfBirth = new DateTime(2022, 10, 6, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(8985),
                            EnclosureId = -6,
                            Name = "animal_101",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -102,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9009),
                            DateOfBirth = new DateTime(2020, 9, 20, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9008),
                            EnclosureId = -2,
                            Name = "animal_102",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -103,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9026),
                            DateOfBirth = new DateTime(2020, 7, 13, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9025),
                            EnclosureId = -4,
                            Name = "animal_103",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -104,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9044),
                            DateOfBirth = new DateTime(2018, 4, 26, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9043),
                            EnclosureId = -4,
                            Name = "animal_104",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -105,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9062),
                            DateOfBirth = new DateTime(2019, 11, 1, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9060),
                            EnclosureId = -6,
                            Name = "animal_105",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -106,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9079),
                            DateOfBirth = new DateTime(2018, 3, 5, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9078),
                            EnclosureId = -2,
                            Name = "animal_106",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -107,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9097),
                            DateOfBirth = new DateTime(2022, 4, 2, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9096),
                            EnclosureId = -1,
                            Name = "animal_107",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -108,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9115),
                            DateOfBirth = new DateTime(2021, 4, 28, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9114),
                            EnclosureId = -5,
                            Name = "animal_108",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -109,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9132),
                            DateOfBirth = new DateTime(2016, 3, 29, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9131),
                            EnclosureId = -3,
                            Name = "animal_109",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -110,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9167),
                            DateOfBirth = new DateTime(2016, 12, 18, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9166),
                            EnclosureId = -3,
                            Name = "animal_110",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9185),
                            DateOfBirth = new DateTime(2022, 5, 20, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9183),
                            EnclosureId = -6,
                            Name = "animal_111",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -112,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9202),
                            DateOfBirth = new DateTime(2020, 9, 13, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9201),
                            EnclosureId = -2,
                            Name = "animal_112",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -113,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9220),
                            DateOfBirth = new DateTime(2020, 9, 5, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9218),
                            EnclosureId = -1,
                            Name = "animal_113",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -114,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9236),
                            DateOfBirth = new DateTime(2022, 4, 1, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9235),
                            EnclosureId = -1,
                            Name = "animal_114",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -115,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9254),
                            DateOfBirth = new DateTime(2016, 1, 25, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9253),
                            EnclosureId = -3,
                            Name = "animal_115",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -116,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9272),
                            DateOfBirth = new DateTime(2023, 4, 11, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9271),
                            EnclosureId = -4,
                            Name = "animal_116",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -117,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9289),
                            DateOfBirth = new DateTime(2016, 9, 5, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9288),
                            EnclosureId = -5,
                            Name = "animal_117",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -118,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9306),
                            DateOfBirth = new DateTime(2023, 5, 15, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9305),
                            EnclosureId = -3,
                            Name = "animal_118",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -119,
                            DateOfAquisition = new DateTime(2024, 3, 13, 12, 26, 36, 994, DateTimeKind.Utc).AddTicks(9323),
                            DateOfBirth = new DateTime(2022, 9, 14, 11, 26, 36, 994, DateTimeKind.Utc).AddTicks(9322),
                            EnclosureId = -1,
                            Name = "animal_119",
                            Sex = 1,
                            SpeciesId = -11
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Capacity = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = -2,
                            Capacity = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = -3,
                            Capacity = 10,
                            Type = 2
                        },
                        new
                        {
                            Id = -4,
                            Capacity = 10,
                            Type = 3
                        },
                        new
                        {
                            Id = -5,
                            Capacity = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = -6,
                            Capacity = 10,
                            Type = 5
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 3,
                            Name = "species_2"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 3,
                            Name = "species_3"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 5,
                            Name = "species_4"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 0,
                            Name = "species_5"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 1,
                            Name = "species_6"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 5,
                            Name = "species_7"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 2,
                            Name = "species_8"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 1,
                            Name = "species_9"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 2,
                            Name = "species_10"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 3,
                            Name = "species_11"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
